'use client';
import {useEffect,useState} from 'react';import Link from 'next/link';
type Source={id:string;jurisdiction:string;stateName:string;authority:string;sourceTitle:string;sourceUrl:string};
type Draft={id:string;jurisdiction:string;stateName:string;version:string;status:string;requirements:{id:string;label:string;sourceTitle:string;sourceUrl:string;citationNote:string}[]};
export default function LegalRuleDrafts(){
 const [sources,setSources]=useState<Source[]>([]);const [drafts,setDrafts]=useState<Draft[]>([]);const [message,setMessage]=useState('');
 async function refresh(){const r=await fetch('/api/admin/legal-rule-drafts',{cache:'no-store'});const b=await r.json();if(!r.ok)throw new Error(b.error);setSources(b.sources);setDrafts(b.drafts)}
 useEffect(()=>{refresh().catch(e=>setMessage(e.message))},[]);
 async function post(payload:unknown){const r=await fetch('/api/admin/legal-rule-drafts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const b=await r.json();if(!r.ok)throw new Error(b.error);setMessage('Rule draft updated.');await refresh()}
 return <main className="dashboardPage"><h1>State rule drafting workbench</h1><p>Transform accepted official sources into structured requirements. Every requirement retains source provenance. Drafts cannot publish from this screen.</p><p role="status">{message}</p><section className="dashCard"><h2>Accepted sources</h2>{sources.map(s=><div className="historyItem" key={s.id}><strong>{s.jurisdiction} · {s.sourceTitle}</strong><span>{s.authority}</span><a href={s.sourceUrl} target="_blank" rel="noreferrer">Open source ↗</a></div>)}</section>{drafts.map(d=><section className="dashCard" key={d.id}><span>{d.jurisdiction} / {d.status.toUpperCase()}</span><h2>{d.stateName} · {d.version}</h2>{d.requirements.map(r=><div key={r.id}><strong>{r.label}</strong><p>Source: <a href={r.sourceUrl} target="_blank" rel="noreferrer">{r.sourceTitle}</a></p><p>Mapping note: {r.citationNote}</p></div>)}{d.status==='draft'&&<button onClick={()=>void post({action:'ready',id:d.id,humanAttestation:true}).catch(e=>setMessage(e.message))}>Attest provenance and send to rule review</button>}</section>)}<p>Draft creation is API-backed and intentionally requires structured, source-linked requirement data; bulk AI extraction is not auto-published.</p><Link href="/admin/legal-sources">← Source ingestion</Link> · <Link href="/admin/legal-rules">Legal rule governance →</Link></main>
}
