'use client';
import {useEffect,useState} from 'react';import Link from 'next/link';
type Item={id:string;jurisdiction:string;stateName:string;authority:string;sourceTitle:string;sourceUrl:string;sourceType:string;priority:number;status:string;note:string};
export default function LegalSources(){
 const [items,setItems]=useState<Item[]>([]);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 async function refresh(){const r=await fetch('/api/admin/legal-sources',{cache:'no-store'});const b=await r.json();if(!r.ok)throw new Error(b.error);setItems(b.items)}
 useEffect(()=>{refresh().catch(e=>setMessage(e.message))},[]);
 async function submit(payload:unknown){setBusy(true);try{const r=await fetch('/api/admin/legal-sources',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const b=await r.json();if(!r.ok)throw new Error(b.error);setMessage('Legal-source queue updated.');await refresh()}catch(e){setMessage(e instanceof Error?e.message:'Unable to update source queue.')}finally{setBusy(false)}}
 return <main className="dashboardPage"><h1>Legal source ingestion</h1><p>Official-source candidates are collected here before rule drafting. Source acceptance requires human review and does not publish legal guidance.</p><p role="status">{message}</p><section className="dashCard"><h2>Queue official source</h2><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void submit({action:'queue',data:{jurisdiction:String(f.get('jurisdiction')),authority:String(f.get('authority')),sourceTitle:String(f.get('sourceTitle')),sourceUrl:String(f.get('sourceUrl')),sourceType:String(f.get('sourceType')),priority:Number(f.get('priority')),note:String(f.get('note')||'')}})}}><label>State code<input name="jurisdiction" required minLength={2} maxLength={5} placeholder="CA"/></label><label>Authority<input name="authority" required/></label><label>Source title<input name="sourceTitle" required/></label><label>Official HTTPS source<input name="sourceUrl" type="url" required/></label><label>Source type<select name="sourceType"><option value="dmv">DMV</option><option value="dot">DOT</option><option value="statute">Statute</option><option value="regulation">Regulation</option><option value="official_guidance">Official guidance</option></select></label><label>Priority<select name="priority"><option value="1">1 — highest</option><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5 — lowest</option></select></label><label>Queue note<textarea name="note" maxLength={1000}/></label><button disabled={busy}>Add source candidate</button></form></section>{items.map(item=><section className="dashCard" key={item.id}><span>{item.jurisdiction} / P{item.priority} / {item.status.toUpperCase()}</span><h2>{item.sourceTitle}</h2><p>{item.authority} · {item.sourceType}</p><a href={item.sourceUrl} target="_blank" rel="noreferrer">Open official source ↗</a>{item.status!=='accepted'&&item.status!=='superseded'&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void submit({action:'transition',data:{id:item.id,to:String(f.get('to')),note:String(f.get('note')),humanAttestation:f.get('humanAttestation')==='on'}})}}><label>Transition<select name="to"><option value="retrieved">Retrieved</option><option value="reviewing">Reviewing</option><option value="accepted">Accept source</option><option value="rejected">Reject</option><option value="superseded">Supersede</option></select></label><label>Review note<textarea name="note" required minLength={10}/></label><label><input type="checkbox" name="humanAttestation"/> I personally verified the official source, authority, scope and effective dates.</label><button disabled={busy}>Record source transition</button></form>}</section>)}<Link href="/admin/legal-rules">Legal rule governance →</Link></main>;
}
