'use client';
import {useEffect,useRef,useState} from 'react';import Link from 'next/link';
type Rollout={summary:{total:number;published:number;pending:number;needsAttention:number;coveragePercent:number};states:{code:string;name:string;status:string;legalGuidanceReady:boolean;reason:string;sourceUrl?:string;validUntil?:string}[]};
type Item={rule:{id:string;jurisdiction:string;stateName?:string;version:string;sourceUrl:string;validUntil:string};digest:string;review:{status:string}|null;resolution:{status:string;reason:string}};
export default function LegalRules(){const [items,setItems]=useState<Item[]>([]);const [rollout,setRollout]=useState<Rollout>();const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const pending=useRef('');
 async function refresh(){const r=await fetch('/api/admin/legal-rules',{cache:'no-store'});const b=await r.json();if(!r.ok)throw new Error(b.error);setItems(b.items);setRollout(b.rollout)}
 useEffect(()=>{refresh().catch(e=>setMessage(e.message))},[]);
 async function send(item:Item,to:string,note:string){setBusy(true);const body=JSON.stringify({ruleId:item.rule.id,digest:item.digest,to,note,humanAttestation:true});pending.current=body;try{const r=await fetch('/api/admin/legal-rules',{method:'POST',headers:{'content-type':'application/json'},body});const b=await r.json();if(!r.ok)throw new Error(b.error);setMessage(`${item.rule.jurisdiction} moved to ${to}.`);await refresh()}catch(e){setMessage(e instanceof Error?e.message:'Unable to save review.')}finally{setBusy(false)}}
 return <main className="dashboardPage"><h1>Legal rule governance</h1><p>Authorized human reviewers control which state-law snapshots may drive user-facing guidance. Expired, unpublished, retired, or superseded rules fail closed.</p><p role="status">{message}</p>{rollout&&<><section className="dashCard"><span>NATIONAL COVERAGE</span><h2>{rollout.summary.published} / {rollout.summary.total} states legally ready · {rollout.summary.coveragePercent}%</h2><p>{rollout.summary.pending} packages pending · {rollout.summary.needsAttention} need lifecycle attention. All 50 states remain selectable; this metric only counts governed legal guidance.</p></section><section className="dashCard"><span>50-STATE ROLLOUT</span><h2>Legal package status</h2>{rollout.states.map(state=><div className="historyItem" key={state.code}><strong>{state.code} · {state.name}</strong><span>{state.status.toUpperCase()} · {state.legalGuidanceReady?'LEGAL GUIDANCE READY':'FAIL-CLOSED'}</span></div>)}</section></>}{items.map(item=><section className="dashCard" key={item.rule.id}><span>{item.rule.stateName||item.rule.jurisdiction} / {item.resolution.status.toUpperCase()}</span><h2>{item.rule.version}</h2><p>{item.resolution.reason}</p><p>Valid until {item.rule.validUntil.slice(0,10)} · review state {item.review?.status||'bootstrap published'}</p><a href={item.rule.sourceUrl} target="_blank" rel="noreferrer">Open official source ↗</a><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void send(item,String(f.get('to')),String(f.get('note')))}}><label>Transition<select name="to"><option value="review">Send to review</option><option value="approved">Approve source review</option><option value="published">Publish</option><option value="superseded">Supersede</option><option value="retired">Retire</option></select></label><label>Reviewer rationale<textarea name="note" required minLength={10} maxLength={1000}/></label><label><input type="checkbox" required/> I personally reviewed the official source and effective dates for this transition.</label><button disabled={busy}>Record transition</button></form></section>)}<Link href="/admin">Back to platform operations</Link></main>;
}
