'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {BrandLogo} from '@/components/BrandLogo';import {BrandLoader} from '@/components/BrandLoader';import {HelpChat} from '@/components/HelpChat';
import {drivingLessons,lessonProgress} from '@/lib/driving-lessons';import {initialState,type State} from '@/lib/domain';

export default function LearnPage(){
 const [loadError,setLoadError]=useState('');
 const [state,setState]=useState<State>(initialState());const [loading,setLoading]=useState(true);const [selected,setSelected]=useState(drivingLessons[0].id);const [feedback,setFeedback]=useState('');
 useEffect(()=>{fetch('/api/pilot',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load progress.');setState(d.state)}).catch(e=>setLoadError(e.message)).finally(()=>setLoading(false))},[]);
 const lessons=useMemo(()=>lessonProgress(state.lessonAttempts.filter(x=>x.completedAt).map(x=>x.lessonId)),[state]);const lesson=lessons.find(x=>x.id===selected)||lessons[0];
 async function answer(scenarioId:string,choiceId:string){setFeedback('');const r=await fetch('/api/lessons',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lessonId:lesson.id,scenarioId,choiceId})});const d=await r.json();if(d.state)setState(d.state);setFeedback(d.feedback||d.error||'Saved.')}
 async function complete(){const r=await fetch('/api/lessons',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lessonId:lesson.id,complete:true})});const d=await r.json();if(d.state)setState(d.state);setFeedback(d.error||'Lesson completed. Choose the next available lesson.')}
 if(loadError)return <main className="dashboardPage"><h1>Your learning workspace</h1><p role="alert">{loadError}</p><Link href="/pilot">Sign in or complete family setup</Link></main>;
 if(loading)return <BrandLoader label="Loading driving lessons"/>;
 return <main className="learnPage"><header className="dashboardHeader"><BrandLogo/><nav><Link href="/dashboard/teen">Teen dashboard</Link><Link href="/pilot">Journey</Link></nav></header><section className="learnHero"><span>ACE + CRUZE / LEARN → PRACTICE → REFLECT</span><h1>Driving lessons built<br/>around real decisions.</h1><p>Scenarios happen while parked. Practice happens with a supervisor and the phone away.</p></section><div className="learnLayout"><aside>{lessons.map(l=><button key={l.id} disabled={l.status==='not_started'} className={selected===l.id?'active':''} onClick={()=>{setSelected(l.id);setFeedback('')}}><small>{l.id} · {l.status.replace('_',' ')}</small><strong>{l.title}</strong></button>)}</aside><article className="lessonBody"><span>{lesson.category.replace('_',' ').toUpperCase()}</span><h2>{lesson.title}</h2><p>{lesson.objective}</p><div className="lessonPractice"><strong>Supervised practice focus</strong><p>{lesson.practiceFocus}</p></div>{lesson.scenarios.map(s=><section className="scenarioCard" key={s.id}><small>SCENARIO / {s.id}</small><h3>{s.title}</h3><p>{s.prompt}</p>{s.choices.map(c=><button key={c.id} onClick={()=>answer(s.id,c.id)}>{c.label}</button>)}</section>)}{feedback&&<div className="message">{feedback}</div>}<div className="parentDebrief"><strong>Parent debrief</strong><p>{lesson.parentDebrief}</p></div><button className="primary" disabled={lesson.status==='not_started'} onClick={complete}>Mark lesson complete →</button><small className="lessonBoundary">Lesson completion is educational progress only. It does not establish legal licensing eligibility or replace supervised instruction required by your jurisdiction.</small></article></div><HelpChat context="lessons"/></main>
}
