import {randomBytes,randomUUID,scryptSync,timingSafeEqual,createHash} from 'node:crypto';
import {db,transaction} from './db';
import type {User} from './types';
export class AppError extends Error {constructor(message:string,public status=400){super(message)}}
export const hash=(value:string)=>createHash('sha256').update(value).digest('hex');
export function rateLimit(key:string,limit=20,windowMs=15*60*1000){return transaction(()=>{const now=Date.now();const row=db().prepare('SELECT * FROM rate_limits WHERE key=?').get(key);if(row&&Number(row.reset_at)>now&&Number(row.count)>=limit)return false;db().prepare('INSERT INTO rate_limits VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET count=excluded.count,reset_at=excluded.reset_at').run(key,row&&Number(row.reset_at)>now?Number(row.count)+1:1,row&&Number(row.reset_at)>now?row.reset_at:now+windowMs);return true})}
function passwordHash(password:string,salt=randomBytes(16).toString('hex')){return `${salt}:${scryptSync(password,salt,64).toString('hex')}`}
export function register(email:string,password:string,name:string):User{const normalized=email.toLowerCase().trim();return transaction(()=>{if(db().prepare('SELECT id FROM users WHERE email=?').get(normalized))throw new AppError('Unable to create this account. Try signing in.',409);const user={id:randomUUID(),email:normalized,name};db().prepare('INSERT INTO users VALUES(?,?,?,?,?)').run(user.id,user.email,passwordHash(password),name,new Date().toISOString());return user})}
export function login(email:string,password:string):User{const row=db().prepare('SELECT * FROM users WHERE email=?').get(email.trim().toLowerCase());const stored=String(row?.password||`${'0'.repeat(32)}:${'0'.repeat(128)}`);const [salt,digest]=stored.split(':');const computed=passwordHash(password,salt).split(':')[1];if(!timingSafeEqual(Buffer.from(computed,'hex'),Buffer.from(digest,'hex'))||!row)throw new AppError('Email or password is incorrect.',401);return {id:String(row.id),email:String(row.email),name:String(row.name)}}
export function createSession(user:User){const token=randomBytes(32).toString('base64url');db().prepare('DELETE FROM sessions WHERE expires_at < ?').run(new Date().toISOString());db().prepare('INSERT INTO sessions VALUES(?,?,?)').run(hash(token),user.id,new Date(Date.now()+7*86400000).toISOString());return token}
export function authenticate(token:string|undefined):User{if(!token)throw new AppError('Sign in to continue.',401);const row=db().prepare('SELECT users.id,users.name,users.email FROM sessions JOIN users ON users.id=sessions.user_id WHERE hash=? AND expires_at>?').get(hash(token),new Date().toISOString());if(!row)throw new AppError('Your session expired. Sign in again.',401);return row as User}
export function logout(token:string){db().prepare('DELETE FROM sessions WHERE hash=?').run(hash(token))}
export function userById(id:string){const row=db().prepare('SELECT id,name,email FROM users WHERE id=?').get(id);return row as User|undefined}
