import {beforeEach,afterEach,it,expect} from 'vitest';
import {mkdtempSync,rmSync,readFileSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {register,createSession} from './auth';
import {closeDatabases,all,put} from './db';
import {execute} from './service';
import {readLegacyLearning,writeLegacyLearning} from './legacy-learning';
import type {User,Profile,Relationship} from './types';
import {GET as pilot,POST as retiredMutation} from '@/app/api/pilot/route';
import {GET as lessons,POST as submit} from '@/app/api/lessons/route';
import {GET as catalog} from '@/app/api/lessons/catalog/route';
import {GET as operations} from '@/app/api/os/status/route';
import {drivingLessons} from '../driving-lessons';
let dir:string;
beforeEach(()=>{dir=mkdtempSync(join(tmpdir(),'legacy-security-'));process.env.TEENSURANCE_DB_PATH=join(dir,'security.sqlite')});
afterEach(async ()=>{(await closeDatabases());delete process.env.TEENSURANCE_DB_PATH;rmSync(dir,{recursive:true,force:true})});
async function family(label:string){
 const parent=(await register(`${label}p@example.test`,'long-password-123','Parent'));const teen=(await register(`${label}t@example.test`,'long-password-123','Teen'));
 const created=(await execute(parent,{action:'household.create',name:'Family',adultAttestation:true},randomUUID())) as {result:{id:string}};const householdId=created.result.id;
 const invite=(await execute(parent,{action:'invite.create',householdId,role:'teen'},randomUUID())) as {result:{token:string}};
 (await execute(teen,{action:'invite.accept',token:invite.result.token},randomUUID()));
 (await execute(teen,{action:'profile.save',householdId,teenId:teen.id,name:'Teen',birthDate:'2010-01-01',jurisdiction:'TX',stage:'permit',goalMinutes:1800,permitDate:'2025-01-01',suspensionDays:0},randomUUID()));
 (await execute(parent,{action:'consent.set',householdId,teenId:teen.id,granted:true},randomUUID()));return {parent,teen,householdId};
}
async function request(path:string,user?:User,payload?:unknown,headers:Record<string,string>={}){return new Request(`http://localhost${path}`,{method:payload?'POST':'GET',headers:{...(user?{cookie:`teensurance_session=${(await createSession(user))}`} : {}),origin:'http://localhost','content-type':'application/json',...headers},...(payload?{body:JSON.stringify(payload)}:{})})}
const action=()=>({lessonId:drivingLessons[0].id,complete:true});
it.each([['pilot',pilot],['lessons',lessons]] as const)('%s denies unauthenticated and forged identity headers',async(path,get)=>{const response=await get((await request(`/api/${path}`,undefined,undefined,{'x-user-id':randomUUID(),'x-role':'guardian','x-household-id':randomUUID()})));expect(response.status).toBe(401);expect(await response.json()).not.toHaveProperty('state')});
it('denies unauthenticated lesson writes and retires legacy mutations',async()=>{expect((await submit((await request('/api/lessons',undefined,action())))).status).toBe(401);expect(retiredMutation().status).toBe(410)});
it('retires global operations without exposing private projections',async()=>{expect(operations().status).toBe(410);expect(Object.keys(await operations().json())).toEqual(['error'])});
it('serves only stable public lesson definitions',async()=>{const data=await catalog().json();expect(Object.keys(data)).toEqual(['lessons']);expect(data.lessons.length).toBeGreaterThan(0)});
it('persists only own progress and allows linked guardian reads',async ()=>{const a=(await family('a'));const b=(await family('b'));(await writeLegacyLearning(a.teen,action()));expect((await readLegacyLearning(a.teen)).state.lessonAttempts).toHaveLength(1);expect((await readLegacyLearning(a.parent)).state.lessonAttempts).toHaveLength(1);expect((await readLegacyLearning(b.teen)).state.lessonAttempts).toEqual([]);(await closeDatabases());expect((await readLegacyLearning(a.teen)).state.lessonAttempts).toHaveLength(1)});
it.each(['pilot','lessons'])('%s denies cross-household and cross-teen query selection',async(path)=>{const a=(await family('a'));const b=(await family('b'));const get=path==='pilot'?pilot:lessons;for(const user of [a.parent,a.teen]){for(const query of [`householdId=${b.householdId}&teenId=${b.teen.id}`,`householdId=${a.householdId}&teenId=${b.teen.id}`])expect((await get((await request(`/api/${path}?${query}`,user)))).status).toBe(403)}expect((await get((await request(`/api/${path}?householdId=${a.householdId}&teenId=${a.teen.id}`,a.parent)))).status).toBe(200)});
it('service boundary rejects cross-household and unrelated IDs directly',async ()=>{const a=(await family('a'));const b=(await family('b'));for(const user of [a.parent,a.teen]){await expect((async()=>(await readLegacyLearning(user,{householdId:b.householdId,teenId:b.teen.id})))()).rejects.toThrow('access denied');await expect((async()=>(await writeLegacyLearning(user,{...action(),householdId:b.householdId,teenId:b.teen.id})))()).rejects.toThrow('access denied')}expect((await all('lesson_progress'))).toEqual([])});
it.each(['role','guardianId','userId','id'])('rejects injected %s in body and query',async(field)=>{const a=(await family('a'));expect((await submit((await request('/api/lessons',a.teen,{...action(),[field]:'guardian'})))).status).toBe(400);expect((await pilot((await request(`/api/pilot?${field}=guardian`,a.teen)))).status).toBe(400);expect((await all('lesson_progress'))).toEqual([])});
it('does not let forged headers override authenticated identity',async()=>{const a=(await family('a'));const b=(await family('b'));const response=await submit((await request('/api/lessons',a.teen,{...action(),householdId:b.householdId,teenId:b.teen.id},{'x-user-id':b.teen.id,'x-role':'guardian'})));expect(response.status).toBe(403);expect((await all('lesson_progress'))).toEqual([])});
it('denies guardian answer impersonation and cross-origin writes',async()=>{const a=(await family('a'));expect((await submit((await request('/api/lessons',a.parent,action())))).status).toBe(403);expect((await submit((await request('/api/lessons',a.teen,action(),{origin:'https://evil.test'})))).status).toBe(403)});
it('denies revoked guardian relationships, consent and adult sharing',async ()=>{const a=(await family('a'));const profile=(await all<Profile>('profile'))[0];(await put('profile',{...profile,consent:false}));await expect((async()=>(await readLegacyLearning(a.teen)))()).rejects.toThrow('consent');(await put('profile',{...profile,birthDate:'2000-01-01',adultSharing:false}));await expect((async()=>(await readLegacyLearning(a.parent)))()).rejects.toThrow('access denied');(await put('profile',profile));const relationship=(await all<Relationship>('relationship'))[0];(await put('relationship',{...relationship,active:false}));await expect((async()=>(await readLegacyLearning(a.parent,{householdId:a.householdId,teenId:a.teen.id})))()).rejects.toThrow('access denied')});
it('denies lesson interactions while an authenticated drive is active',async ()=>{const a=(await family('a'));(await execute(a.teen,{action:'drive.start',householdId:a.householdId,teenId:a.teen.id,supervisorId:a.parent.id,skill:'Parking',supervisorEligible:true},randomUUID()));await expect((async()=>(await writeLegacyLearning(a.teen,action())))()).rejects.toThrow('parking');await expect((async()=>(await readLegacyLearning(a.parent)))()).rejects.toThrow('parking')});
it('no API imports the shared JSON store',()=>{function walk(path:string):string[]{return readdirSync(path,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(join(path,e.name)):[join(path,e.name)])}for(const path of walk('app/api').filter(p=>p.endsWith('route.ts')))expect(readFileSync(path,'utf8'),path).not.toMatch(/(?:from|import).*['"](?:@\/lib\/store|[^'"]*\/store)['"]/) });

it('denies a sibling in the same household and unlinked guardians',async ()=>{const a=(await family('a'));const sibling=(await register('sibling@example.test','long-password-123','Sibling'));const invite=(await execute(a.parent,{action:'invite.create',householdId:a.householdId,role:'teen'},randomUUID())) as {result:{token:string}};(await execute(sibling,{action:'invite.accept',token:invite.result.token},randomUUID()));await expect((async()=>(await readLegacyLearning(sibling,{householdId:a.householdId,teenId:a.teen.id})))()).rejects.toThrow('access denied');const b=(await family('b'));await expect((async()=>(await readLegacyLearning(b.parent,{householdId:a.householdId,teenId:a.teen.id})))()).rejects.toThrow('access denied')});
it('preserves mixed night-minute progress in the authenticated projection',async ()=>{const a=(await family('a'));const d=(await execute(a.teen,{action:'drive.manual',householdId:a.householdId,teenId:a.teen.id,supervisorId:a.parent.id,skill:'Parking',supervisorEligible:true,startedAt:'2026-01-01T12:00:00.000Z',minutes:30,nightMinutes:10,note:''},randomUUID())) as {result:{id:string}};(await execute(a.parent,{action:'drive.review',householdId:a.householdId,id:d.result.id,decision:'confirm',reason:''},randomUUID()));expect((await readLegacyLearning(a.teen)).state.logs[0]).toMatchObject({minutes:30,nightMinutes:10,status:'verified'})});
