import {randomBytes} from 'node:crypto';
import {db,transaction} from './db';import {requireAdmin} from './admin';import type {User} from './types';
export const errorCategories=['AUTH_FAILURE','MEMBERSHIP_FAILURE','HOUSEHOLD_ACCESS_DENIED','PERSISTENCE_FAILURE','CONTENT_UNAVAILABLE','PASSPORT_UPDATE_FAILURE','INVITATION_FAILURE'] as const;
export type ErrorCategory=typeof errorCategories[number];
export async function recordFailure(category:ErrorCategory){const reference=`TS-${randomBytes(6).toString('hex').toUpperCase()}`;const at=new Date().toISOString();console.error(JSON.stringify({reference,category,at}));try{await db().prepare('INSERT INTO operational_errors(reference,category,at) VALUES(?,?,?)').run(reference,category,at)}catch{/* The minimal server log remains available during a database outage. */}return reference}
async function educationalMetrics(){
 const count=async(kind:string,extra='',args:unknown[]=[])=>Number((await db().prepare(`SELECT COUNT(*) AS count FROM records WHERE kind=? ${extra}`).get(kind,...args))?.count||0);
 const households=async(kind:string,extra='',args:unknown[]=[])=>Number((await db().prepare(`SELECT COUNT(DISTINCT household_id) AS count FROM records WHERE kind=? AND household_id IN (SELECT household_id FROM records WHERE kind='pilot_enrollment') ${extra}`).get(kind,...args))?.count||0);
 const weeklySince=new Date(Date.now()-7*86400000).toISOString();
 const attempts=await count('roadready_attempt');const misses=await count('roadready_attempt',"AND CAST(json_extract(payload,'$.correct') AS TEXT) IN ('false','0')");
 const concepts=await count('roadready_mastery');const demonstrated=await count('roadready_mastery',"AND json_extract(payload,'$.state') IN ('demonstrated','reinforced')");const reinforced=await count('roadready_mastery',"AND json_extract(payload,'$.state')='reinforced'");
 const recommendations=await count('scout_plan');const completedRecommendations=await count('scout_plan',"AND json_extract(payload,'$.status')='completed'");
 const permitTopics=Number((await db().prepare("SELECT COUNT(DISTINCT json_extract(payload,'$.conceptId')) AS count FROM records WHERE kind='permit_attempt'").get())?.count||0);
 return {funnel:{invited:await count('pilot_invite'),guardianActivated:await count('pilot_enrollment'),teenLinked:await households('relationship',"AND json_extract(payload,'$.kind')='guardian'"),teenOnboarded:await households('pilot_orientation'),firstRoadReady:await households('roadready_event',"AND json_extract(payload,'$.name') IN ('learning_session_started','hazard_scene_started','permit_prep_started','review_started')"),firstDemonstrated:await households('roadready_mastery',"AND json_extract(payload,'$.state') IN ('demonstrated','reinforced')"),guardianReinforcement:await households('roadready_guardian'),activeLastSevenDays:await households('roadready_event',"AND json_extract(payload,'$.at')>=?",[weeklySince])},learning:{attempts,incorrectAttemptRate:attempts?misses/attempts:null,trackedConcepts:concepts,demonstrationRate:concepts?demonstrated/concepts:null,reinforcementRate:concepts?reinforced/concepts:null,scoutRecommendationCompletionRate:recommendations?completedRecommendations/recommendations:null,permitTopicsPracticed:permitTopics},definitions:'Funnel stages after invitations count distinct enrolled households; invitations count codes. Learning rates describe all persisted educational activity, not driving risk. Null means no denominator.'};
}
export async function operations(user:User){requireAdmin(user);return transaction(async()=>{const counts=await db().prepare('SELECT kind,COUNT(*) AS count FROM records GROUP BY kind').all();const accounts=await db().prepare('SELECT COUNT(*) AS count FROM users').get();const pilotStates=await db().prepare("SELECT json_extract(payload,'$.status') AS status,COUNT(*) AS count FROM records WHERE kind='pilot_enrollment' GROUP BY json_extract(payload,'$.status')").all();const pilotEnrollments=await db().prepare("SELECT id,household_id,json_extract(payload,'$.cohortId') AS cohort_id,json_extract(payload,'$.status') AS status,json_extract(payload,'$.jurisdiction') AS jurisdiction,json_extract(payload,'$.updatedAt') AS updated_at FROM records WHERE kind='pilot_enrollment' ORDER BY rowid DESC LIMIT 100").all();const eventCounts=await db().prepare("SELECT json_extract(payload,'$.name') AS name,COUNT(*) AS count,COUNT(DISTINCT household_id) AS households FROM records WHERE kind IN ('pilot_event','roadready_event') GROUP BY json_extract(payload,'$.name')").all();const feedback=(await db().prepare("SELECT id,json_extract(payload,'$.itemId') AS item_id,json_extract(payload,'$.category') AS category,json_extract(payload,'$.note') AS note,json_extract(payload,'$.status') AS status FROM records WHERE kind='content_feedback' ORDER BY rowid DESC LIMIT 50").all());const errors=await db().prepare('SELECT reference,category,at FROM operational_errors ORDER BY at DESC LIMIT 30').all();return {educational:await educationalMetrics(),feedback,pilotStates:Object.fromEntries(pilotStates.map(r=>[String(r.status),Number(r.count)])),pilotEnrollments:pilotEnrollments.map(r=>({id:String(r.id),householdId:String(r.household_id),cohortId:String(r.cohort_id||''),status:String(r.status||''),jurisdiction:String(r.jurisdiction||''),updatedAt:String(r.updated_at||'')})),events:Object.fromEntries(eventCounts.map(r=>[String(r.name),{occurrences:Number(r.count),households:Number(r.households)}])),accounts:Number(accounts?.count||0),records:Object.fromEntries(counts.map(r=>[String(r.kind),Number(r.count)])),errors,pilotEnabled:process.env.PILOT_ENABLED==='true',analyticsBoundary:'Educational product operations only; never insurance underwriting.'}})}
