'use client';
import {useEffect,useState} from 'react';import Link from 'next/link';
type Alert={id:string;jurisdiction:string;ruleId:string;version:string;severity:string;status:string;reasons:string[];affected:string[];assignedTo:string;dueAt:string;note:string};
export default function LegalEscalations(){
 const [items,setItems]=useState<Alert[]>([]);const [message,setMessage]=useState('');
 async function load(){const r=await fetch('/api/admin/legal-escalations',{cache:'no-store'});const b=await r.json();if(!r.ok)throw new Error(b.error);setItems(b.items)}
 useEffect(()=>{load().catch(e=>setMessage(e.message))},[]);
 async function act(id:string,action:'acknowledge'|'resolve'){const note=action==='acknowledge'?'Reviewer acknowledged recertification escalation.':'Reviewer confirmed operational escalation is resolved; legal publication remains separately governed.';const r=await fetch('/api/admin/legal-escalations',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id,action,note})});const b=await r.json();if(!r.ok)throw new Error(b.error);setMessage('Escalation updated.');await load()}
 return <main className="dashboardPage"><h1>Legal change escalations</h1><p>Operational alerts track recertification work. Resolving an alert does not approve or publish a legal rule.</p><p role="status">{message}</p>{items.filter(x=>x.status!=='resolved').map(a=><section className="dashCard" key={a.id}><span>{a.severity.toUpperCase()} · {a.status.toUpperCase()}</span><h2>{a.jurisdiction} · {a.ruleId}</h2><p>Owner: {a.assignedTo} · Due: {new Date(a.dueAt).toLocaleString()}</p><p>Reasons: {a.reasons.join(', ')}</p><p>Affected: {a.affected.join(', ')}</p><p>{a.note}</p>{a.status==='open'&&<button onClick={()=>void act(a.id,'acknowledge').catch(e=>setMessage(e.message))}>Acknowledge</button>}<button onClick={()=>void act(a.id,'resolve').catch(e=>setMessage(e.message))}>Resolve operational alert</button></section>)}{!items.some(x=>x.status!=='resolved')&&<section className="dashCard"><h2>No open legal escalations</h2></section>}<Link href="/admin/legal-recertification">Recertification impacts</Link> · <Link href="/admin/legal-rules">Legal governance</Link></main>
}
