 'use client';
import {useEffect,useState} from 'react';
import type {inspectReviews} from '@/lib/scout/review-service';
type Item=Awaited<ReturnType<typeof inspectReviews>>[number];
export function ContentReview(){const [items,setItems]=useState<Item[]>([]);const [message,setMessage]=useState('Loading authorized review queue...');const [busy,setBusy]=useState(false);
 async function load(){const r=await fetch('/api/admin/content');const b=await r.json();if(!r.ok){setItems([]);setMessage(b.error);return}setItems(b.items);setMessage('Review original content and its linked source. Automated validation is not human approval.')}
 useEffect(()=>{void load().catch(()=>setMessage('Unable to load review queue.'))},[]);
 return <section><h2>Human content review</h2><p role="status">{message}</p>{items.map(i=><details key={i.id}><summary>{i.name} · {i.jurisdiction} · {i.review?.status||'draft'} · {i.version}</summary><a href={i.sourceUrl} target="_blank" rel="noreferrer">Review source</a><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(i.content,null,2)}</pre><p>Reviewer: {i.review?.reviewer||'REVIEW REQUIRED'}; date: {i.review?.reviewedAt||'not recorded'}</p><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{const r=await fetch('/api/admin/content',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({itemId:i.id,digest:i.digest,to:f.get('to'),note:f.get('note'),humanAttestation:f.get('attest')==='on'})});const b=await r.json();if(!r.ok)setMessage(b.error);else await load()}catch{setMessage('Unable to save review. Reload before retrying.')}finally{setBusy(false)}}}><label>Transition<select name="to"><option value="review">Submit for review</option><option value="approved">Approve reviewed content</option><option value="published">Publish approved version</option><option value="retired">Retire version</option></select></label><label>Review rationale<textarea name="note" required minLength={10} maxLength={1000}/></label><label><input type="checkbox" name="attest"/>I personally reviewed this exact content and its authoritative sources.</label><button disabled={busy}>Record transition</button></form></details>)}</section>
}
