'use client';
import {useCallback,useEffect,useState} from 'react';
import Image from 'next/image';
import Link from 'next/link';
import {BrandLogo} from './BrandLogo';
import type {Dashboard} from '@/lib/platform/types';
import {modes,type ConceptMastery,type GuardianReinforcement,type LearningEvidence,type LearningSession,type RoadLearningConcept,type ScoutRecommendation} from '@/lib/roadready/types';
type Session=LearningSession&{challenge:{id:string;conceptId:string;prompt:string;options:{id:string;text:string}[]}|null};
type Data={role:string;concepts:RoadLearningConcept[];mastery:ConceptMastery[];evidence:LearningEvidence[];guardianEvidence:GuardianReinforcement[];session:Session|null;recommendation:ScoutRecommendation;priorityStep:{title:string;reason:string};passport:(ConceptMastery&{provenance:string;claim:string})[]};
const label=(text:string)=>text.replaceAll('_',' ');
export function RoadReady(){
 const [workspace,setWorkspace]=useState<Dashboard|null>(null);const [data,setData]=useState<Data|null>(null);const [teenId,setTeenId]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [parked,setParked]=useState(false);const [choice,setChoice]=useState('');const [feedback,setFeedback]=useState<{correct:boolean;explanation:string}|null>(null);const [category,setCategory]=useState('regulatory_sign');
 const [register,setRegister]=useState(false);
 const loadWorkspace=useCallback(async()=>{try{const response=await fetch('/api/workspace',{cache:'no-store'});if(response.ok){const w:Dashboard=await response.json();setWorkspace(w);setTeenId(w.profiles[0]?.ownerId||'')}else if(response.status!==401)setMessage('Unable to load your family.')}catch{setMessage('Connection problem. Try again.')}finally{setLoading(false)}},[]);
 useEffect(()=>{void loadWorkspace()},[loadWorkspace]);
 const refresh=useCallback(async()=>{if(!workspace?.household||!teenId)return;try{const r=await fetch(`/api/roadready?householdId=${workspace.household.id}&teenId=${teenId}`,{cache:'no-store'});const body=await r.json();if(r.ok)setData(body.data);else{setData(null);setMessage(body.error)}}catch{setMessage('Could not load learning progress.')}},[workspace,teenId]);
 useEffect(()=>{setData(null);setFeedback(null);setChoice('');void refresh()},[refresh]);
 async function send(payload:Record<string,unknown>){setBusy(true);setMessage('');try{const response=await fetch('/api/roadready',{method:'POST',headers:{'Content-Type':'application/json','idempotency-key':crypto.randomUUID()},body:JSON.stringify({...payload,householdId:workspace?.household?.id,teenId,context:'PARKED'})});const body=await response.json();if(!response.ok){setMessage(body.error);return null}await refresh();return body.result}catch{setMessage('Connection problem. Reload to check your saved progress.');return null}finally{setBusy(false)}}
 async function account(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:register?'register':'login',email:form.get('email'),password:form.get('password'),...(register?{name:form.get('name')}:{})})});const body=await r.json();if(!r.ok)setMessage(body.error);else await loadWorkspace()}catch{setMessage('Could not sign in.')}finally{setBusy(false)}}
 async function family(event:React.FormEvent<HTMLFormElement>,action:string){event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);const payload:Record<string,unknown>=Object.fromEntries(form);payload.action=action;if(action==='household.create')payload.adultAttestation=true;if(action==='profile.save'){Object.assign(payload,{householdId:workspace?.household?.id,teenId:workspace?.user.id,jurisdiction:'TX',stage:'pre-permit',goalMinutes:1800,permitDate:'',suspensionDays:0})}try{const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json','idempotency-key':crypto.randomUUID()},body:JSON.stringify(payload)});const body=await r.json();if(!r.ok)setMessage(body.error);else await loadWorkspace()}catch{setMessage('Could not save family setup.')}finally{setBusy(false)}}
 const current=data?.session?.challenge;const concept=data?.concepts.find(c=>c.id===current?.conceptId);const visible=data?.concepts.filter(c=>category==='all'||c.category===category)||[];
 return <main className="dashboardPage roadready"><header className="dashboardHeader"><BrandLogo/><nav aria-label="RoadReady navigation"><Link href="/dashboard/teen">Teen dashboard</Link><Link href="/dashboard/parent">Guardian dashboard</Link><Link href="/pilot?tab=passport">Passport</Link></nav></header>
 <section className="dashboardHero"><div><span>ROADREADY / SCOUT</span><h1>Notice more.<br/>Understand why.</h1><p>Build road knowledge one thoughtful decision at a time.</p></div></section>
 <p className="rrSafety">RoadReady is for learning and preparation. Do not use Teensurance while driving.</p>
 {message&&<p role="alert">{message}</p>}{loading&&<p role="status">Loading your learning space…</p>}
 {!loading&&!workspace&&<section className="dashCard"><h2>{register?'Create your family account':'Sign in to RoadReady'}</h2><form onSubmit={account}>{register&&<label>Your name<input name="name" autoComplete="name" required minLength={2}/></label>}<label>Email<input name="email" type="email" autoComplete="email" required/></label><label>Password<input name="password" type="password" autoComplete={register?'new-password':'current-password'} minLength={register?12:1} required/></label><button disabled={busy}>{register?'Create account':'Sign in'}</button><button type="button" onClick={()=>setRegister(!register)}>{register?'Already have an account?':'Create a family account'}</button></form></section>}
 {workspace&&!workspace.household&&<section className="dashCard"><h2>Connect your family</h2><form onSubmit={e=>family(e,'invite.accept')}><label>Invitation code<input name="token" required/></label><button disabled={busy}>Join household</button></form><form onSubmit={e=>family(e,'household.create')}><label>Household name<input name="name" required minLength={2}/></label><label><input type="checkbox" required/> I am an adult guardian creating this household.</label><button disabled={busy}>Create household</button></form></section>}
 {workspace?.household&&!workspace.profiles.length&&workspace.membership?.role==='teen'&&<section className="dashCard"><h2>Create your learner profile</h2><form onSubmit={e=>family(e,'profile.save')}><label>Learner name<input name="name" required minLength={2}/></label><label>Birth date<input name="birthDate" type="date" required/></label><p>The initial learning pack covers Texas. Your guardian must consent before learning begins.</p><button disabled={busy}>Save learner profile</button></form></section>}
 {workspace?.household&&workspace.membership?.role==='guardian'&&<FamilyControls workspace={workspace} onChange={loadWorkspace}/>}
 {!!workspace?.profiles.length&&<label>Learner<select value={teenId} onChange={e=>{setTeenId(e.target.value);setMessage('')}}>{workspace.profiles.map(p=><option key={p.ownerId} value={p.ownerId}>{p.name}</option>)}</select></label>}
 {data&&<><section className="dashCard"><span>YOUR JOURNEY FIRST</span><h2>{data.priorityStep.title}</h2><p>{data.priorityStep.reason}</p><Link href="/pilot">Review journey requirements</Link></section>
 <label className="rrParked"><input type="checkbox" checked={parked} onChange={e=>setParked(e.target.checked)}/> I am safely parked or away from the vehicle.</label>
 <div className="dashboardGrid"><section className="dashCard accentCard"><span>SCOUT RECOMMENDS</span><h2>Practice {data.concepts.find(c=>c.id===data.recommendation.conceptId)?.name}</h2><p>{data.recommendation.reason}</p>{data.role==='teen'&&<button disabled={busy||!parked} onClick={async()=>{if(await send({action:'accept_recommendation',recommendationId:data.recommendation.id})){await send({action:'start',mode:data.recommendation.mode,conceptId:data.recommendation.conceptId});setFeedback(null)}}}>Practice recommendation</button>}</section>
 <section className="dashCard"><h2>Learning progress</h2><div className="rrCounts">{['introduced','practicing','demonstrated','reinforced'].map(s=><p key={s}><strong>{data.mastery.filter(m=>m.state===s).length}</strong> {s}</p>)}</div><p>Demonstration takes three distinct observations on separate days. One answer does not establish mastery.</p></section></div>
 {data.role==='teen'&&<section className="dashCard"><h2>Game modes</h2><div className="rrModes">{modes.map(mode=><button key={mode} disabled={busy||!parked||!!data.session} onClick={async()=>{setChoice('');setFeedback(null);await send({action:'start',mode})}}>{mode}</button>)}</div></section>}
 {data.role==='teen'&&(current||feedback)&&<section className="dashCard rrChallenge" aria-label="Learning challenge"><h2>{data.session?'Continue Learning':'Session complete'}</h2>{feedback?<div role="status"><h3>{feedback.correct?'You recognized it.':'Let’s take another look.'}</h3><p>{feedback.explanation}</p><p>Your learning evidence has been saved.</p><button onClick={()=>{setFeedback(null);setChoice('')}}>{current?'Next challenge':'Return to learning'}</button></div>:current&&<form onSubmit={async e=>{e.preventDefault();const result=await send({action:'answer',sessionId:data.session!.id,challengeId:current.id,answerId:choice});if(result)setFeedback(result)}}>{concept&&<Image src={concept.imageAsset} alt={concept.assetLabel} width={320} height={300}/>}<fieldset disabled={busy||!parked}><legend>{current.prompt}</legend>{current.options.map(option=><label className="rrOption" key={option.id}><input type="radio" name="answer" value={option.id} checked={choice===option.id} onChange={()=>setChoice(option.id)} required/>{option.text}</label>)}</fieldset><button disabled={busy||!parked||!choice}>Check answer</button></form>}</section>}
 <div className="dashboardGrid"><section className="dashCard"><h2>Needs Another Look</h2>{data.mastery.filter(m=>m.state==='practicing').map(m=><p key={m.conceptId}>{data.concepts.find(c=>c.id===m.conceptId)?.name} — practicing{m.retryAt?`. Revisit after ${new Date(m.retryAt).toLocaleDateString()}.`:''}</p>)}{!data.mastery.some(m=>m.state==='practicing')&&<p>No concepts waiting for a retry.</p>}</section><section className="dashCard"><h2>Recently Demonstrated</h2>{data.mastery.filter(m=>['demonstrated','reinforced'].includes(m.state)).map(m=><p key={m.conceptId}>{data.concepts.find(c=>c.id===m.conceptId)?.name} — {m.state}</p>)}{!data.mastery.some(m=>['demonstrated','reinforced'].includes(m.state))&&<p>Your later observations will build this evidence.</p>}</section></div>
 <section className="dashCard"><h2>Categories</h2><label>Explore concepts<select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All categories</option>{Array.from(new Set(data.concepts.map(c=>c.category))).map(c=><option key={c} value={c}>{label(c)}</option>)}</select></label><div className="rrConcepts">{visible.map(c=><details key={c.id}><summary>{c.name} · {label(data.mastery.find(m=>m.conceptId===c.id)!.state)}</summary><p>{c.explanation}</p><a href={c.sourceUrl} target="_blank" rel="noreferrer">Official source: {c.sourceSection}</a>{data.role==='guardian'?<div><p>While safely parked, ask your learner to explain {c.name} and a careful response. Discuss it before the next drive.</p><button disabled={busy||!parked} onClick={()=>send({action:'reinforce',conceptId:c.id,completed:true})}>Completed</button><button disabled={busy||!parked} onClick={()=>send({action:'reinforce',conceptId:c.id,completed:false})}>Needs more practice</button></div>:<button disabled={busy||!parked||!!data.session} onClick={async()=>{setFeedback(null);await send({action:'start',mode:c.category==='road_marking'?'Road Markings':c.category==='traffic_signal'?'Signal Sense':c.category==='dashboard_symbol'||c.category==='guide_sign'?'Symbol Match':c.category.endsWith('_sign')?'Sign Snap':'What Would You Do?',conceptId:c.id})}}>Practice this concept</button>}</details>)}</div></section>
 <section className="dashCard" id="road-knowledge"><span>SAFETY & READINESS PASSPORT</span><h2>Road Knowledge &amp; Awareness</h2><p>Learning evidence describes understanding. It does not establish legal eligibility, insurance approval, or driving safety.</p>{Array.from(new Set(data.concepts.map(c=>c.category))).map(category=>{const ids=new Set(data.concepts.filter(c=>c.category===category).map(c=>c.id));const entries=data.passport.filter(m=>ids.has(m.conceptId)&&m.state!=='not_started');return <details key={category}><summary>{label(category)} — {entries.filter(m=>m.state==='demonstrated').length} demonstrated, {entries.filter(m=>m.state==='reinforced').length} reinforced, {entries.filter(m=>m.state==='practicing').length} practicing</summary>{entries.map(m=><article key={m.conceptId}><h3>{data.concepts.find(c=>c.id===m.conceptId)?.name}: {m.state}</h3><p>{m.provenance}</p></article>)}{!entries.length&&<p>No learning evidence yet.</p>}</details>})}</section>
 <section className="dashCard"><h2>Recent learning</h2>{data.evidence.slice(-10).reverse().map(e=><p key={e.id}>{data.concepts.find(c=>c.id===e.conceptId)?.name} — {e.correct?'recognized':'another look'} · {new Date(e.at).toLocaleDateString()}</p>)}{data.guardianEvidence.slice(-5).map(e=><p key={e.id}>Guardian parked practice: {data.concepts.find(c=>c.id===e.conceptId)?.name} — {e.completed?'completed':'needs practice'}</p>)}</section></>}
 </main>;
}
function FamilyControls({workspace,onChange}:{workspace:Dashboard;onChange:()=>Promise<void>}){
 const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 async function command(payload:Record<string,unknown>){setBusy(true);try{const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json','idempotency-key':crypto.randomUUID()},body:JSON.stringify({...payload,householdId:workspace.household!.id})});const body=await r.json();setMessage(r.ok?(body.result?.token?`Invitation code: ${body.result.token}`:'Saved.'):body.error);if(r.ok)await onChange()}catch{setMessage('Could not save.')}finally{setBusy(false)}}
 return <details className="dashCard"><summary>Family learning access</summary><button disabled={busy} onClick={()=>command({action:'invite.create',role:'teen'})}>Create teen invitation</button>{workspace.profiles.filter(p=>!p.consent).map(p=><p key={p.id}>{p.name}: <button disabled={busy} onClick={()=>command({action:'consent.set',teenId:p.ownerId,granted:true})}>Grant learning and practice consent</button></p>)}<p role="status">{message}</p></details>;
}
