 'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import Image from 'next/image';
import type {readScoutIntelligence} from '@/lib/scout/intelligence-service';
import type {PracticeSession,SafeContext} from '@/lib/roadready/intelligence-types';
type Data=NonNullable<ReturnType<typeof readScoutIntelligence>['data']>;
type Props={householdId:string;teenId:string;parked:boolean;onEvidence:()=>Promise<void>};
export function ScoutIntelligence({householdId,teenId,parked,onEvidence}:Props){
 const [data,setData]=useState<Data|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [selected,setSelected]=useState('');const [targets,setTargets]=useState<string[]>([]);const [answer,setAnswer]=useState('');const [interpreted,setInterpreted]=useState(false);const [feedback,setFeedback]=useState<{correct:boolean;explanation:string;kind:string}|null>(null);const [activityContext,setActivityContext]=useState<SafeContext>('AT_HOME');const [conceptId,setConceptId]=useState('');const pending=useRef<{signature:string;key:string}>();
 const refresh=useCallback(async()=>{try{const r=await fetch(`/api/scout/intelligence?householdId=${householdId}&teenId=${teenId}`,{cache:'no-store'});const body=await r.json();if(!r.ok){setData(null);setError(body.error);return}setData(body.data);setError('')}catch{setError('Unable to load learning activities.')}},[householdId,teenId]);
 useEffect(()=>{setData(null);setSelected('');setFeedback(null);setTargets([]);setAnswer('');void refresh()},[refresh]);
 async function send(payload:Record<string,unknown>){setBusy(true);setError('');const signature=JSON.stringify({...payload,householdId,teenId,context:activityContext});if(pending.current?.signature!==signature)pending.current={signature,key:crypto.randomUUID()};try{const r=await fetch('/api/scout/intelligence',{method:'POST',headers:{'Content-Type':'application/json','idempotency-key':pending.current.key},body:signature});const body=await r.json();if(!r.ok){pending.current=undefined;setError(body.error);return null}pending.current=undefined;await refresh();await onEvidence();return body.result}catch{setError('Connection interrupted. Retry the same action to check its saved result.');return null}finally{setBusy(false)}}
 async function start(kind:PracticeSession['kind'],itemId?:string,recommendationId?:string){const result=await send({action:'start',kind,itemId,recommendationId});if(result){setSelected(result.id);setFeedback(null);setTargets([]);setAnswer('');setInterpreted(false)}}
 const session=data?.sessions.find(s=>s.id===selected)||data?.sessions[0];const item=session?.item;
 if(!data)return <section className="dashCard"><h2>Today with Scout</h2><p role={error?'alert':'status'}>{error||'Loading learning activities...'}</p></section>;
 const rec=data.recommendation;
 return <div className="rrIntelligence">
 {error&&<p role="alert">{error}</p>}{data.fallback&&<p role="status">{data.fallback}</p>}
 <section className="dashCard accentCard"><span>SCOUT / ONE NEXT STEP</span><h2>Today with Scout</h2><h3>{rec.title}</h3><p>{rec.reason}</p>{data.role==='teen'&&<><button disabled={busy||!parked} onClick={()=>{if(rec.type==='resume_session'){setSelected(rec.conceptId);document.getElementById('intelligence-activity')?.scrollIntoView()}else void start(rec.type==='start_hazard_scene'?'hazard':'review',rec.conceptId,rec.id)}}>Start Scout activity</button><button disabled={busy||!parked||rec.priority<2} onClick={()=>send({action:'dismiss',recommendationId:rec.id})}>Choose another topic</button></>}{data.role==='guardian'&&<button disabled={busy||!parked} onClick={()=>send({action:'coach_start',conceptId:rec.conceptId})}>Start recommended family activity</button>}</section>
 {data.role==='teen'&&<div className="dashboardGrid"><section className="dashCard"><span>NOTICE / INTERPRET / RESPOND</span><h2>Spot What Matters</h2><p>Study a still road scene, identify what needs attention, then choose a careful response.</p><label>Road scene<select value={conceptId} onChange={e=>setConceptId(e.target.value)}><option value="">First scene</option>{data.hazards.map(h=><option key={h.id} value={h.id}>{h.title}</option>)}</select></label><button disabled={busy||!parked} onClick={()=>start('hazard',conceptId||undefined)}>Start hazard scene</button></section>
 <section className="dashCard"><span>KNOWLEDGE PREPARATION</span><h2>Permit Prep</h2><p>Jurisdiction: {data.jurisdiction}</p><p>Practice content for learning and preparation. Official licensing requirements and tests are administered by the relevant state authority.</p><p>{data.permit.completed} practice sessions completed · {data.permit.coverage} topics practiced.</p><button disabled={busy||!parked||!!data.fallback} onClick={()=>start('permit')}>Start Permit Prep</button><h3>Review missed concepts</h3>{data.permit.missed.map(id=><p key={id}>{data.coachConcepts.find(c=>c.id===id)?.name||id}</p>)}<p>Practice progress is separate from Passport evidence. No passing prediction is provided.</p></section></div>}
 {data.role==='teen'&&(session||feedback)&&<section id="intelligence-activity" className="dashCard rrChallenge" aria-label="Intelligence activity"><h2>{session?`Continue ${session.kind==='permit'?'Permit Prep':session.kind==='hazard'?'Spot What Matters':'targeted review'}`:'Activity complete'}</h2>{data.sessions.length>1&&<label>Resume activity<select value={session?.id||''} onChange={e=>{setSelected(e.target.value);setFeedback(null);setAnswer('');setTargets([]);setInterpreted(false)}}>{data.sessions.map(s=><option key={s.id} value={s.id}>{s.kind}</option>)}</select></label>}
 {feedback?<div role="status"><h3>{feedback.correct?'Thoughtfully recognized.':'Needs another look.'}</h3><p>{feedback.explanation}</p><p>{feedback.kind==='permit'?'Practice saved separately from Passport.':'Learning evidence saved with its source version.'}</p><button onClick={()=>{setFeedback(null);setAnswer('');setTargets([]);setInterpreted(false)}}>{session?'Continue activity':'Return to activities'}</button></div>:item&&<form onSubmit={async e=>{e.preventDefault();const result=await send({action:'answer',sessionId:session!.id,itemId:item.id,answerId:answer,...(item.type==='hazard'?{targets}:{})});if(result)setFeedback(result)}}>
 {item.type==='hazard'?<><h3>{item.title}</h3><Image src={item.imageAsset} alt={item.description} width={600} height={400}/><p>{item.description}</p><fieldset disabled={busy||!parked}><legend>Identify what matters in this scene</legend>{item.hazardTargets.map(t=><label className="rrOption" key={t.id}><input type="checkbox" checked={targets.includes(t.id)} onChange={e=>{setTargets(e.target.checked?[...targets,t.id]:targets.filter(id=>id!==t.id));setInterpreted(false)}}/>{t.label}</label>)}</fieldset><button type="button" disabled={!targets.length} onClick={()=>setInterpreted(true)}>Consider why this matters</button>{interpreted&&<p>Think about how the selected road user, surface or blocked view could change the available path. Choose a response that leaves time and space.</p>}<fieldset disabled={busy||!parked||!interpreted}><legend>What is the safest response?</legend>{item.responseOptions.map(o=><label className="rrOption" key={o.id}><input type="radio" name="intelligence-answer" required checked={answer===o.id} onChange={()=>setAnswer(o.id)}/>{o.text}</label>)}</fieldset></>:<fieldset disabled={busy||!parked}><legend>{item.prompt}</legend>{item.options.map(o=><label className="rrOption" key={o.id}><input type="radio" name="intelligence-answer" required checked={answer===o.id} onChange={()=>setAnswer(o.id)}/>{o.text}</label>)}</fieldset>}
 <button disabled={busy||!parked||!answer||(item.type==='hazard'&&!interpreted)}>Save thoughtful response</button></form>}{session&&!item&&!feedback&&<p role="alert">This content is no longer published. Choose another available activity.</p>}</section>}
 {data.role==='guardian'&&<section className="dashCard"><h2>Guardian Coach</h2><p>Before or after a drive, at home, or while parked: ask your learner what matters, why, and how they would respond. Never interact with the app while moving.</p><label>Activity setting<select value={activityContext} onChange={e=>setActivityContext(e.target.value as SafeContext)}>{['AT_HOME','PARKED','PRE_DRIVE','POST_DRIVE'].map(c=><option key={c}>{c}</option>)}</select></label><label>Family discussion topic<select value={conceptId} onChange={e=>setConceptId(e.target.value)}><option value="">Choose a concept</option>{data.coachConcepts.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button disabled={!conceptId||busy||!parked} onClick={()=>send({action:'coach_start',conceptId})}>Begin guardian activity</button>{data.coach.map(a=><article key={a.id}><h3>{a.title}</h3><p>{a.context} · {a.status.replaceAll('_',' ')}</p>{a.status==='started'&&<><button disabled={busy||!parked} onClick={()=>send({action:'coach_complete',activityId:a.id,completed:true})}>Confirm family reinforcement</button><button disabled={busy||!parked} onClick={()=>send({action:'coach_complete',activityId:a.id,completed:false})}>Record more practice needed</button></>}</article>)}</section>}
 <section className="dashCard" id="hazard-passport"><span>ROAD KNOWLEDGE &amp; AWARENESS / PASSPORT</span><h2>Hazard Awareness</h2><p>Educational observations, not a driver-risk score or safety certification.</p>{data.hazardPassport.map(m=><p key={m.conceptId}>{m.name}: {m.state.replaceAll('_',' ')} · {m.qualifyingObservations} qualifying observations</p>)}<h3>Recent hazard evidence</h3>{data.recentEvidence.map(e=><p key={e.id}>{data.hazards.find(h=>h.id===e.challengeId)?.title}: {e.correct?'recognized':'needs another look'} · {e.contentVersion}</p>)}</section>
 </div>;
}
