import {test,expect,type Page,type BrowserContext} from '@playwright/test';

async function account(page:Page,name:string,email:string){await page.goto('/pilot');await page.getByRole('button',{name:'New here? Create an account'}).click();await page.getByLabel('Your name').fill(name);await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill('Certification-password-123');await page.getByRole('button',{name:'Create account',exact:true}).click();await expect(page.getByRole('heading',{name:'Connect your family.'})).toBeVisible()}
async function nav(page:Page,name:string){await page.getByRole('navigation',{name:'Main navigation'}).getByRole('button',{name,exact:true}).click()}
async function request(context:BrowserContext,payload:unknown){return context.request.post('/api/workspace',{headers:{origin:'http://127.0.0.1:3100','idempotency-key':crypto.randomUUID()},data:payload})}
test('guardian → invitation → teen profile → consent → session → supervisor ledger → evidence → reminders',async({browser})=>{
 const guardianContext=await browser.newContext();const teenContext=await browser.newContext();const guardian=await guardianContext.newPage();const teen=await teenContext.newPage();const stamp=Date.now();const errors:string[]=[];guardian.on('pageerror',e=>errors.push(e.message));teen.on('pageerror',e=>errors.push(e.message));
 await account(guardian,'Guardian',`guardian-${stamp}@example.test`);await guardian.getByLabel('Household name').fill('Road together');await guardian.getByLabel('I am an adult guardian creating this household.').check();await guardian.getByRole('button',{name:'Create household',exact:true}).click();await expect(guardian.getByRole('heading',{name:/Every mile has/})).toBeVisible();
 await nav(guardian,'My family');await guardian.getByRole('button',{name:'Create invitation',exact:true}).click();const link=await guardian.getByLabel('Invitation link').inputValue();expect(link).toContain('?invite=');
 await account(teen,'Teen',`teen-${stamp}@example.test`);await teen.getByLabel('Invitation code').fill(new URL(link).searchParams.get('invite')!);await teen.getByRole('button',{name:'Join household',exact:true}).click();await expect(teen.getByRole('heading',{name:/Every mile has/})).toBeVisible();
 await nav(teen,'Driver profile');await teen.getByLabel('Birth date').fill('2010-01-01');await teen.getByLabel('Driving stage').selectOption('permit');await teen.getByLabel('Permit issue date (if held)').fill('2025-01-01');await teen.getByRole('button',{name:'Save driver profile',exact:true}).click();await expect(teen.getByText('Guardian consent required',{exact:true})).toBeVisible();
 await guardian.reload();await nav(guardian,'Driver profile');await guardian.getByRole('button',{name:'Grant consent',exact:true}).click();await expect(guardian.getByText('Guardian consent granted',{exact:true})).toBeVisible();
 await teen.reload();await nav(teen,'Drive & hours');const plan=teen.getByRole('heading',{name:'Plan your practice'}).locator('..');const startForm=plan.locator('form').first();await startForm.getByLabel('Supervisor',{exact:true}).selectOption({label:'Guardian'});await startForm.getByLabel('Practice focus').fill('Quiet streets');await startForm.getByRole('checkbox').check();await startForm.getByRole('button',{name:'Start drive',exact:true}).click();await expect(teen.getByRole('heading',{name:/Eyes up/})).toBeVisible();await teen.reload();await expect(teen.getByRole('heading',{name:/Eyes up/})).toBeVisible();
 const active=await (await teenContext.request.get('/api/workspace')).json();const deferred=await request(teenContext,{action:'agent.explain',householdId:active.household.id,teenId:active.user.id});expect(deferred.status()).toBe(403);
 await teen.getByRole('button',{name:'I’m parked — finish drive'}).click();await nav(teen,'Drive & hours');const draft=teen.locator('.driveCard').filter({hasText:'Quiet streets'});await draft.getByLabel('Total minutes').fill('30');await draft.getByLabel('Night minutes').fill('10');await draft.getByRole('button',{name:'Submit for supervisor review'}).click();await expect(draft.getByText('pending',{exact:true})).toBeVisible();
 await guardian.reload();await nav(guardian,'Drive & hours');const review=guardian.locator('.driveCard').filter({hasText:'Quiet streets'});await review.getByRole('checkbox').check();await review.getByRole('button',{name:'Submit attestation'}).click();await expect(review.getByText('verified',{exact:true})).toBeVisible();
 await teen.reload();await nav(teen,'My journey');await expect(teen.locator('.stat').first()).toContainText('0h 30m');await teen.getByRole('button',{name:'Ask T for direction'}).click();await expect(teen.locator('.sourceNotice')).toContainText('Your next step:');
 await nav(teen,'Evidence & approvals');await teen.getByLabel('What was completed?').fill('Reviewed the permit preparation checklist');await teen.getByRole('button',{name:'Request review'}).click();await expect(teen.locator('.evidenceItem')).toContainText('pending');
 await guardian.reload();await nav(guardian,'Evidence & approvals');await guardian.getByRole('button',{name:'Accept evidence'}).click();await expect(guardian.locator('.evidenceItem')).toContainText('accepted');
 await nav(teen,'Reminders');await teen.getByLabel('Reminder',{exact:true}).fill('Review the permit checklist');await teen.getByLabel('When (local time)').fill('2027-01-01T12:00');await teen.getByRole('button',{name:'Add reminder'}).click();await expect(teen.getByText('Review the permit checklist',{exact:true})).toBeVisible();await teen.getByRole('button',{name:'Done',exact:true}).click();
 await teen.setViewportSize({width:390,height:844});await nav(teen,'My journey');await expect(teen.getByRole('heading',{name:/Every mile has/})).toBeVisible();expect(await teen.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await teen.screenshot({path:'docs/screenshots/certified-journey-mobile.png',fullPage:true});
 await guardian.setViewportSize({width:1536,height:1024});await nav(guardian,'My journey');await guardian.screenshot({path:'docs/screenshots/certified-guardian-desktop.png',fullPage:true});expect(errors).toEqual([]);await guardianContext.close();await teenContext.close();
});

test('separate accounts cannot read or mutate another household',async({browser})=>{const a=await browser.newContext();const b=await browser.newContext();const pa=await a.newPage();const pb=await b.newPage();const stamp=Date.now();await account(pa,'First',`first-${stamp}@example.test`);await pa.getByLabel('Household name').fill('First household');await pa.getByRole('checkbox').first().check();await pa.getByRole('button',{name:'Create household',exact:true}).click();await expect(pa.getByRole('heading',{name:/Every mile has/})).toBeVisible();const data=await (await a.request.get('/api/workspace')).json();await account(pb,'Second',`second-${stamp}@example.test`);expect((await b.request.get(`/api/workspace?household=${data.household.id}`)).status()).toBe(403);expect((await request(b,{action:'invite.create',householdId:data.household.id,role:'teen'})).status()).toBe(403);expect((await b.request.post('/api/pilot',{data:{action:'verify',role:'parent'}})).status()).toBe(410);await a.close();await b.close()});


test('legacy learning stays private through browser refresh and forged scope requests',async({browser})=>{
 const context=await browser.newContext();const stranger=await browser.newContext();const stamp=Date.now();
 const register=async(ctx:BrowserContext,name:string)=>{const r=await ctx.request.post('/api/auth',{headers:{origin:'http://127.0.0.1:3100'},data:{action:'register',email:`${name}-${stamp}@example.test`,password:'Certification-password-123',name}});expect(r.status()).toBe(200)};
 await register(context,'Guardian');const h=await (await request(context,{action:'household.create',name:'Learning household',adultAttestation:true})).json();const householdId=h.result.id;
 const invitation=await (await request(context,{action:'invite.create',householdId,role:'teen'})).json();
 const learner=await browser.newContext();await register(learner,'Learner');await request(learner,{action:'invite.accept',token:invitation.result.token});
 const workspace=await (await learner.request.get('/api/workspace')).json();const teenId=workspace.user.id;
 expect((await request(learner,{action:'profile.save',householdId,teenId,name:'Learner',birthDate:'2010-01-01',jurisdiction:'TX',stage:'permit',goalMinutes:1800,permitDate:'2025-01-01',suspensionDays:0})).status()).toBe(200);
 expect((await request(context,{action:'consent.set',householdId,teenId,granted:true})).status()).toBe(200);
 const page=await learner.newPage();const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/learn');await page.getByRole('button',{name:'Mark lesson complete'}).click();await expect(page.getByText('Lesson completed. Choose the next available lesson.')).toBeVisible();await page.reload();
 expect((await (await learner.request.get('/api/lessons')).json()).attempts).toHaveLength(1);
 expect((await (await context.request.get(`/api/lessons?householdId=${householdId}&teenId=${teenId}`)).json()).attempts).toHaveLength(1);
 await register(stranger,'Unrelated');for(const path of ['pilot','lessons'])expect((await stranger.request.get(`/api/${path}?householdId=${householdId}&teenId=${teenId}`)).status()).toBe(403);
 await page.goto('/dashboard/teen');await expect(page.getByRole('heading',{name:/Your road/})).toBeVisible();await page.goto('/admin');await expect(page.getByText(/Private operations require explicitly configured/)).toBeVisible();expect(errors).toEqual([]);
 await context.close();await stranger.close();await learner.close();
});
