import {test,expect,type Browser,type BrowserContext,type Page} from '@playwright/test';
import {createRequire} from 'node:module';
import {randomUUID} from 'node:crypto';
import {challenges} from '../lib/roadready/content';
const origin='http://127.0.0.1:3101';
const request=(context:BrowserContext,url:string,data:unknown)=>{
 const input=data as Record<string,unknown>;const q=challenges.find(q=>q.id===input.challengeId);
 const answerId=input.answerId==='meaning'?q?.answerId:input.answerId==='misconception'?q?.options.find(o=>o.id!==q.answerId)?.id:undefined;
 return context.request.post(url,{headers:{origin,'idempotency-key':randomUUID()},data:answerId?{...input,answerId}:data});
};
async function setup(browser:Browser){
 const guardian=await browser.newContext({baseURL:origin});const teen=await browser.newContext({baseURL:origin});const stamp=randomUUID();
 const p=await (await request(guardian,'/api/auth',{action:'register',name:'Guardian',email:`p-${stamp}@example.test`,password:'Roadready-password-123'})).json();
 const t=await (await request(teen,'/api/auth',{action:'register',name:'Learner',email:`t-${stamp}@example.test`,password:'Roadready-password-123'})).json();
 const h=await (await request(guardian,'/api/workspace',{action:'household.create',name:'Learning family',adultAttestation:true})).json();const householdId=h.result.id;const teenId=t.user.id;
 const invite=await (await request(guardian,'/api/workspace',{action:'invite.create',householdId,role:'teen'})).json();
 expect((await request(teen,'/api/workspace',{action:'invite.accept',token:invite.result.token})).ok()).toBe(true);
 expect((await request(teen,'/api/workspace',{action:'profile.save',householdId,teenId,name:'Learner',birthDate:'2010-01-01',jurisdiction:'TX',stage:'permit',goalMinutes:1800,permitDate:'2025-01-01',suspensionDays:0})).ok()).toBe(true);
 expect((await request(guardian,'/api/workspace',{action:'consent.set',householdId,teenId,granted:true})).ok()).toBe(true);
 return {guardian,teen,householdId,teenId,parentId:p.user.id,email:`t-${stamp}@example.test`};
}
async function open(page:Page){await page.goto('/teen/roadready');await expect(page.getByRole('heading',{name:'Learning progress'})).toBeVisible();await page.getByLabel('I am safely parked or away from the vehicle.').check()}
async function answer(page:Page,correct=true){
 const area=page.getByRole('region',{name:'Learning challenge'});const prompt=await area.locator('legend').innerText();const q=challenges.find(q=>q.prompt===prompt)!;
 const option=q.options.find(o=>correct?o.id===q.answerId:o.id!==q.answerId)!;
 // Exercise native radio/keyboard submission, not just pointer interaction.
 await area.getByLabel(option.text,{exact:true}).focus();await page.keyboard.press('Space');await page.keyboard.press('Tab');await page.keyboard.press('Enter');
 await expect(area.getByText('Your learning evidence has been saved.')).toBeVisible();
}
function seedLaterEvidence(householdId:string,teenId:string){
 // Explicit local fixture for observations on three prior days. Never backdates via production API.
 const {DatabaseSync}=createRequire(`${process.cwd()}/package.json`)('node:sqlite');const database=new DatabaseSync(process.env.ROADREADY_E2E_DB_PATH!);
 for(let day=1;day<=3;day++){const id=randomUUID();const e={id,householdId,ownerId:teenId,teenId,conceptId:'US-TX:stop',sessionId:randomUUID(),challengeId:`US-TX:stop:v${day}`,answerId:'meaning',correct:true,at:new Date(Date.now()-(5-day)*86400000).toISOString(),kind:'learning',contentVersion:'US-TX-2026-09-v1'};database.prepare('INSERT INTO records VALUES(?,?,?,?,?)').run(id,'roadready_attempt',householdId,teenId,JSON.stringify(e))}database.close();
}
test('E2E-01 authenticated login, five shared modes, explanation, persistence, keyboard and responsive layout',async({browser})=>{
 const f=await setup(browser);await request(f.teen,'/api/auth',{action:'logout'});const page=await f.teen.newPage();const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/teen/roadready');await page.getByLabel('Email',{exact:true}).fill(f.email);await page.getByLabel('Password',{exact:true}).fill('Roadready-password-123');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('heading',{name:'Learning progress'})).toBeVisible();await page.getByLabel('I am safely parked or away from the vehicle.').check();
 for(const mode of ['Sign Snap','Symbol Match','Road Markings','Signal Sense','What Would You Do?']){
  await page.getByRole('button',{name:mode,exact:true}).click();const area=page.getByRole('region',{name:'Learning challenge'});
  for(;;){await expect(area.getByRole('button',{name:'Check answer'})).toBeVisible();await answer(page);const next=area.getByRole('button',{name:'Next challenge',exact:true});if(await next.count())await next.click();else{await area.getByRole('button',{name:'Return to learning'}).click();break}}
 }
 await page.reload();await expect(page.getByRole('heading',{name:'Recent learning'})).toBeVisible();await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'docs/screenshots/roadready-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'docs/screenshots/roadready-desktop.png',fullPage:true});await page.keyboard.press('Tab');expect(await page.locator(':focus').count()).toBe(1);expect(errors).toEqual([]);await f.teen.close();await f.guardian.close();
});
test('E2E-02 wrong answer explains and appears in Needs Another Look',async({browser})=>{const f=await setup(browser);const page=await f.teen.newPage();await open(page);await page.getByRole('button',{name:'Practice recommendation'}).click();await answer(page,false);await expect(page.getByRole('heading',{name:'Needs Another Look'}).locator('..')).toContainText('practicing');await f.teen.close();await f.guardian.close()});
test('E2E-03 weak concept resurfaces as an alternative challenge',async({browser})=>{const f=await setup(browser);const command={householdId:f.householdId,teenId:f.teenId,context:'PARKED'};const start=await (await request(f.teen,'/api/roadready',{...command,action:'start',mode:'Sign Snap',conceptId:'US-TX:stop'})).json();await request(f.teen,'/api/roadready',{...command,action:'answer',sessionId:start.result.id,challengeId:start.result.challenge.id,answerId:'misconception'});const next=await (await request(f.teen,'/api/roadready',{...command,action:'start',mode:'Sign Snap',conceptId:'US-TX:stop'})).json();expect(next.result.challenge.id).not.toBe(start.result.challenge.id);const page=await f.teen.newPage();await open(page);await answer(page);const saved=await (await f.teen.request.get(`/api/roadready?householdId=${f.householdId}&teenId=${f.teenId}`)).json();expect(saved.data.evidence).toHaveLength(2);await f.teen.close();await f.guardian.close()});
test('E2E-04 later observations appear in Passport with provenance',async({browser})=>{const f=await setup(browser);seedLaterEvidence(f.householdId,f.teenId);const page=await f.teen.newPage();await open(page);await expect(page.locator('#road-knowledge')).toContainText('STOP: demonstrated');await expect(page.locator('#road-knowledge')).toContainText('3 qualifying learning observations');await page.goto('/pilot?tab=passport');await expect(page.getByRole('heading',{name:'Road Knowledge & Awareness'})).toBeVisible();await expect(page.getByText('1 demonstrated',{exact:true})).toBeVisible();await f.teen.close();await f.guardian.close()});
test('E2E-05 linked guardian parked practice reinforces qualifying evidence',async({browser})=>{const f=await setup(browser);seedLaterEvidence(f.householdId,f.teenId);const page=await f.guardian.newPage();await open(page);const concept=page.locator('details').filter({has:page.locator('summary').filter({hasText:/^STOP ·/})});await concept.locator('summary').click();await concept.getByRole('button',{name:'Completed',exact:true}).click();await expect(page.locator('#road-knowledge')).toContainText('STOP: reinforced');await expect(page.locator('#road-knowledge')).toContainText('1 guardian parked-practice confirmations');await f.teen.close();await f.guardian.close()});
test('E2E-06 unrelated household and forged guardian evidence denied',async({browser})=>{const f=await setup(browser);const outsider=await browser.newContext({baseURL:origin});await request(outsider,'/api/auth',{action:'register',name:'Other',email:`other-${randomUUID()}@example.test`,password:'Roadready-password-123'});expect((await outsider.request.get(`/api/roadready?householdId=${f.householdId}&teenId=${f.teenId}`)).status()).toBe(403);expect((await request(f.teen,'/api/roadready',{action:'reinforce',householdId:f.householdId,teenId:f.teenId,conceptId:'US-TX:stop',completed:true,context:'PARKED'})).status()).toBe(403);await outsider.close();await f.teen.close();await f.guardian.close()});
test('E2E-07 prohibited mechanisms and active-drive interactions denied',async({browser})=>{const f=await setup(browser);for(const action of ['speed_score','miles_competition','drive_count_streak','leaderboard','fastest_answer_ranking','trip_count_reward','in_drive_prompt','insurance_risk_score'])expect((await request(f.teen,'/api/roadready',{action,householdId:f.householdId,teenId:f.teenId,context:'PARKED'})).status()).toBe(400);expect((await request(f.teen,'/api/workspace',{action:'drive.start',householdId:f.householdId,teenId:f.teenId,supervisorId:f.parentId,skill:'Parking',supervisorEligible:true})).ok()).toBe(true);expect((await f.teen.request.get(`/api/roadready?householdId=${f.householdId}&teenId=${f.teenId}`)).status()).toBe(403);await f.teen.close();await f.guardian.close()});
