import {createRequire} from 'node:module';
import {mkdirSync} from 'node:fs';
import {dirname} from 'node:path';
import type {Database,Statement} from './types';
export function sqlite(path:string):Database {
 mkdirSync(dirname(path),{recursive:true});
 const {DatabaseSync}=createRequire(import.meta.url)('node:sqlite');
 const raw=new DatabaseSync(path);
  raw.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;
    CREATE TABLE IF NOT EXISTS operational_errors(reference TEXT PRIMARY KEY,category TEXT NOT NULL,at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS schema_version(version INTEGER PRIMARY KEY);
    INSERT OR IGNORE INTO schema_version VALUES(1);
    CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,password TEXT NOT NULL,name TEXT NOT NULL,created_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS waitlist_entries(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,parent_name TEXT NOT NULL,teen_count INTEGER NOT NULL CHECK(teen_count BETWEEN 1 AND 10),region TEXT NOT NULL,referral_source TEXT NOT NULL DEFAULT '',status TEXT NOT NULL CHECK(status IN ('NEW','CONTACTED','INVITED','ENROLLED','DECLINED')),notes TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
    CREATE INDEX IF NOT EXISTS waitlist_status_created ON waitlist_entries(status,created_at DESC);
    CREATE TABLE IF NOT EXISTS waitlist_events(id TEXT PRIMARY KEY,entry_id TEXT NOT NULL REFERENCES waitlist_entries(id),actor_id TEXT NOT NULL REFERENCES users(id),from_status TEXT NOT NULL,to_status TEXT NOT NULL,note TEXT NOT NULL DEFAULT '',at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS sessions(hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),expires_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS records(id TEXT PRIMARY KEY,kind TEXT NOT NULL,household_id TEXT NOT NULL,owner_id TEXT NOT NULL,payload TEXT NOT NULL CHECK(json_valid(payload)));
    CREATE INDEX IF NOT EXISTS records_scope ON records(kind,household_id,owner_id);
    CREATE TABLE IF NOT EXISTS audit(id TEXT PRIMARY KEY,at TEXT NOT NULL,actor_id TEXT NOT NULL,household_id TEXT NOT NULL,action TEXT NOT NULL,decision TEXT NOT NULL,reason TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS ledger(id TEXT PRIMARY KEY,drive_id TEXT NOT NULL,revision INTEGER NOT NULL,household_id TEXT NOT NULL,teen_id TEXT NOT NULL,minutes INTEGER NOT NULL,night_minutes INTEGER NOT NULL,actor_id TEXT NOT NULL,reason TEXT NOT NULL,at TEXT NOT NULL,UNIQUE(drive_id,revision));
    CREATE TABLE IF NOT EXISTS requests(user_id TEXT NOT NULL,key TEXT NOT NULL,fingerprint TEXT NOT NULL,result TEXT NOT NULL,PRIMARY KEY(user_id,key));
    CREATE TABLE IF NOT EXISTS rate_limits(key TEXT PRIMARY KEY,count INTEGER NOT NULL,reset_at INTEGER NOT NULL);
    CREATE TRIGGER IF NOT EXISTS audit_no_update BEFORE UPDATE ON audit BEGIN SELECT RAISE(ABORT,'Audit is append only'); END;
    CREATE TRIGGER IF NOT EXISTS audit_no_delete BEFORE DELETE ON audit BEGIN SELECT RAISE(ABORT,'Audit is append only'); END;
    CREATE TRIGGER IF NOT EXISTS ledger_no_update BEFORE UPDATE ON ledger BEGIN SELECT RAISE(ABORT,'Ledger is append only'); END;
    CREATE TRIGGER IF NOT EXISTS ledger_no_delete BEFORE DELETE ON ledger BEGIN SELECT RAISE(ABORT,'Ledger is append only'); END;`);
 raw.exec(`CREATE TRIGGER IF NOT EXISTS review_event_no_update BEFORE UPDATE ON records WHEN OLD.kind='content_review_event' BEGIN SELECT RAISE(ABORT,'Review history is append only'); END;
 CREATE TRIGGER IF NOT EXISTS review_event_no_delete BEFORE DELETE ON records WHEN OLD.kind='content_review_event' BEGIN SELECT RAISE(ABORT,'Review history is append only'); END;`);
 return {dialect:'sqlite',exec:async sql=>{raw.exec(sql)},prepare(sql){const s=raw.prepare(sql);return {run:async(...args)=>s.run(...args),get:async(...args)=>s.get(...args),all:async(...args)=>s.all(...args)} as Statement},close:async()=>raw.close()};
}
