import {beforeEach,describe,expect,it,vi} from 'vitest';
const all=vi.fn();const put=vi.fn(async(_k:string,v:unknown)=>v);const transaction=vi.fn(async(fn:()=>unknown)=>fn());const audit=vi.fn();const createQuoteSession=vi.fn();
vi.mock('../platform/db',()=>({all,put,transaction}));vi.mock('../platform/service',()=>({audit}));vi.mock('./service',()=>({createQuoteSession}));
const user={id:'g',name:'Guardian',email:'g@example.com'};
const policy={id:'p',householdId:'h',ownerId:'g',teenId:'t',handoffId:'bh',carrierId:'current',externalPolicyId:'P1',status:'ACTIVE',effectiveAt:'2026-01-01',confirmedAt:'2026-01-01'};
const handoff={id:'bh',householdId:'h',ownerId:'g',teenId:'t',selectionId:'s',carrierId:'current',quoteId:'oldq',state:'ACTIVE',externalReference:'ext',createdAt:'2026-01-01',updatedAt:'2026-01-01'};
const source={id:'qs0',householdId:'h',ownerId:'g',teenId:'t',idempotencyKey:'old',fingerprint:'f',normalizedRequest:{coverageLevel:'standard',vehicles:[{year:2025,make:'Honda',model:'Civic',primaryUse:'school'}]},results:[{carrierId:'current',status:'quoted',quote:{quoteId:'oldq'}}],status:'completed',createdAt:'2026-01-01'};
describe('renewal reshopping',()=>{
 beforeEach(()=>{vi.clearAllMocks();all.mockImplementation((kind:string)=>{if(kind==='member')return Promise.resolve([{id:'m',householdId:'h',ownerId:'g',role:'guardian',name:'G',active:true}]);if(kind==='insurance_policy')return Promise.resolve([policy]);if(kind==='insurance_bind_handoff')return Promise.resolve([handoff]);if(kind==='insurance_carrier_event')return Promise.resolve([{event:{externalReference:'ext',renewalAt:'2026-11-01'}}]);if(kind==='insurance_quote_session')return Promise.resolve([source]);if(kind==='insurance_renewal_decision')return Promise.resolve([]);return Promise.resolve([])});createQuoteSession.mockResolvedValue({...source,id:'qs-new',results:[{carrierId:'new',status:'quoted',quote:{carrierId:'new',quoteId:'newq'}}]})});
 it('detects a 60-day renewal shopping window',async()=>{const {renewalOpportunities}=await import('./renewal');const result=await renewalOpportunities(user,'h',new Date('2026-10-04T00:00:00Z'));expect(result[0]).toMatchObject({policyId:'p',reason:'renewal_window',eligible:true})});
 it('prefills a fresh comparison from existing policy context',async()=>{const {startRenewalReshop}=await import('./renewal');await startRenewalReshop(user,'h','p','renewal_key_123456789');expect(createQuoteSession).toHaveBeenCalledWith(user,expect.objectContaining({intent:'compare_current',teenId:'t',currentPolicy:expect.objectContaining({carrierName:'current'})}),'renewal_key_123456789')});
 it('requires a valid fresh quote before switching',async()=>{const {recordRenewalDecision}=await import('./renewal');all.mockImplementation((kind:string)=>kind==='member'?Promise.resolve([{id:'m',householdId:'h',ownerId:'g',role:'guardian',name:'G',active:true}]):kind==='insurance_policy'?Promise.resolve([policy]):kind==='insurance_quote_session'?Promise.resolve([{...source,id:'qs-new',results:[]}]):Promise.resolve([]));await expect(recordRenewalDecision(user,'h','p','qs-new','switch','new','missing')).rejects.toThrow('valid quoted carrier offer')});
});