'use client';
import {useEffect,useMemo,useState} from 'react';
import {steps, type State, type Role, type DrivingState,progress as calculate,initialState} from '@/lib/domain';
type ResponseData={state:State;progress:ReturnType<typeof calculate>;policy?:{decision:string;reason:string};error?:string};
const today=()=>new Date().toLocaleDateString('en-CA');
export default function Page(){
 const [state,setState]=useState<State>(initialState());const [role,setRole]=useState<Role>('teen');const [driving,setDriving]=useState<DrivingState>('parked');const [tab,setTab]=useState<'journey'|'log'|'family'>('journey');const [selected,setSelected]=useState(2);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 const [form,setForm]=useState({date:today(),minutes:45,night:false,skill:'Quiet streets',supervisor:'',note:''});const [goal,setGoal]=useState(20);
 const p=useMemo(()=>calculate(state),[state]);
 useEffect(()=>{const params=new URLSearchParams(window.location.search);if(params.get('role')==='parent')setRole('parent');if(params.get('tab')==='family')setTab('family');if(params.get('mode')==='drive')setDriving('driving');const step=Number(params.get('step'));if(params.has('step')&&Number.isInteger(step)&&step>=0&&step<steps.length)setSelected(step)},[]);
 useEffect(()=>{fetch('/api/pilot',{cache:'no-store'}).then(r=>r.json()).then((d:ResponseData)=>{setState(d.state);setGoal(d.state.goalHours)}).catch(()=>setMessage('Could not load the pilot. Refresh to try again.')).finally(()=>setLoading(false))},[]);
 async function act(payload:Record<string,unknown>){setBusy(true);setMessage('');try{const response=await fetch('/api/pilot',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,role,drivingState:driving})});const data:ResponseData=await response.json();if(data.state)setState(data.state);if(!response.ok){setMessage(data.policy?.reason||data.error||'Could not save. Try again.');return false}setMessage(data.policy?.reason||'Saved.');return true}catch{setMessage('Connection problem. Please try again.');return false}finally{setBusy(false)}}
 async function submit(e:React.FormEvent){e.preventDefault();const ok=await act({action:'log',...form,minutes:Number(form.minutes)});if(ok){setForm({...form,minutes:45,note:''});setTab('family')}}
 if(driving==='driving')return <main className="driving"><div className="driveMark">T<span>•</span></div><p>Focus on the road.</p><h1>We’ll be here when you’re parked.</h1><button onClick={()=>setDriving('parked')}>I’m parked now</button><small>Only tap after the vehicle is safely parked.</small></main>;
 return <div className="appShell"><aside className="sidebar"><div className="brand"><span className="brandMark">T<span>•</span></span><span>teensurance<small>THE DRIVE, TOGETHER</small></span></div><div className="navLabel">YOUR SPACE</div><nav aria-label="Main navigation"><button className={tab==='journey'?'active':''} onClick={()=>setTab('journey')}><span>◫</span> Journey</button><button className={tab==='log'?'active':''} onClick={()=>setTab('log')}><span>↗</span> Log a drive</button><button className={tab==='family'?'active':''} onClick={()=>setTab('family')}><span>◎</span> Family review {p.pending>0&&<b>{p.pending}</b>}</button></nav><div className="sideBottom"><div className="safetyDot">● &nbsp; GUARD ACTIVE</div><p>Plan and log only while parked. Your practice entries need parent review.</p><button onClick={()=>setDriving('driving')} className="drivingButton">I’m driving now →</button></div></aside>
 <main className="main"><header className="topbar"><span>FAMILY PILOT <span className="slash">/</span> {tab==='journey'?'Journey':tab==='log'?'Log a drive':'Family review'}</span><div className="roleSwitch" aria-label="Pilot role"><button className={role==='teen'?'chosen':''} onClick={()=>setRole('teen')}>Teen view</button><button className={role==='parent'?'chosen':''} onClick={()=>setRole('parent')}>Parent view</button></div></header>
 {loading?<div className="loading">Loading your journey…</div>:<>
 {message&&<div role="status" className="message">{message}<button aria-label="Dismiss notice" onClick={()=>setMessage('')}>×</button></div>}
 {tab==='journey'&&<><section className="intro"><div><div className="eyebrow">YOUR ROADMAP <span>01—05</span></div><h1>Every mile has<br/><em>a next step.</em></h1><p>Know what to do, who helps, and what counts as done.</p></div><div className="introAside"><span>YOUR PRACTICE GOAL</span><strong>{Math.floor(p.verifiedMinutes/60)}<small> / {state.goalHours} hr</small></strong><div className="bar"><i style={{width:`${p.percent}%`}}/></div><small>{p.pending} {p.pending===1?'entry':'entries'} awaiting review · Family goal, not a legal requirement</small></div></section><div className="contentGrid"><section><div className="sectionHead"><h2>The journey</h2><span>Choose a step to see the direction</span></div><div className="steps">{steps.map((s,i)=><button key={s.id} className={`step ${selected===i?'selected':''}`} onClick={()=>setSelected(i)}><span className="stepNum">0{i+1}</span><span className="stepTitle">{s.name}<small>{s.agent} · {i<2?'Get ready':i===2?'Build experience':'Plan ahead'}</small></span><span className="arrow">↗</span></button>)}</div></section><section className="detail" aria-live="polite"><div className="detailTop"><span>STEP 0{selected+1}</span><span className="agent">{steps[selected].agent}</span></div><h2>{steps[selected].name}</h2><p>{steps[selected].detail}</p><div className="detailDivider"/><h3>What counts as complete</h3><p>{steps[selected].proof}</p><div className="sourceNotice">Requirements vary by location. Confirm permit, hour, test, and insurance rules with official sources before making decisions.</div>{selected===2&&<button className="primary" onClick={()=>setTab('log')}>Log a practice drive <span>→</span></button>}</section></div></>}
 {tab==='log'&&<div className="workspace"><div className="pageTitle"><div className="eyebrow">MILES / PRACTICE RECORD</div><h1>Log a drive.</h1><p>Add it after you’re parked. A parent reviews each entry before it counts toward your family goal.</p></div><div className="formGrid"><form onSubmit={submit} className="card formCard"><div className="formHeader"><h2>New supervised session</h2><span>01 / 01</span></div><div className="fields"><label>Date<input type="date" required max={today()} value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Minutes practiced<input type="number" required min="1" max="240" value={form.minutes} onChange={e=>setForm({...form,minutes:Number(e.target.value)})}/></label><label>Focus area<select value={form.skill} onChange={e=>setForm({...form,skill:e.target.value})}><option>Quiet streets</option><option>Turns & intersections</option><option>Parking</option><option>Highway merging</option><option>Night driving</option><option>Other practice</option></select></label><label>Supervisor name<input required minLength={2} maxLength={80} placeholder="Person who rode with you" value={form.supervisor} onChange={e=>setForm({...form,supervisor:e.target.value})}/></label><label className="full checkbox"><input type="checkbox" checked={form.night} onChange={e=>setForm({...form,night:e.target.checked})}/> This session included night driving</label><label className="full">Notes <span className="optional">OPTIONAL</span><textarea maxLength={300} placeholder="What felt easier? What should you practice next?" value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label></div><button type="submit" className="primary" disabled={busy||role!=='teen'}>{busy?'Saving…':'Save for parent review'} <span>→</span></button>{role==='parent'&&<p className="inlineHelp">Switch to Teen view to create a session.</p>}</form><div className="tips"><span className="tag">CRUZE / BEFORE THE NEXT DRIVE</span><h2>Keep the plan simple.</h2><p>Choose one skill, agree on a route with your supervisor, and put the phone away before moving.</p><div className="rule"><strong>01</strong><span>Plan together while parked</span></div><div className="rule"><strong>02</strong><span>Practice with a qualified supervisor</span></div><div className="rule"><strong>03</strong><span>Reflect and log after the drive</span></div></div></div></div>}
 {tab==='family'&&<div className="workspace"><div className="pageTitle"><div className="eyebrow">FAMILY / SHARED PROGRESS</div><h1>Practice, together.</h1><p>Verified entries count toward your family goal. This tracker does not determine licensing eligibility.</p></div><div className="statRow"><div className="stat"><span>VERIFIED PRACTICE</span><strong>{(p.verifiedMinutes/60).toFixed(1)} <small>hr</small></strong></div><div className="stat"><span>NIGHT PRACTICE</span><strong>{(p.nightMinutes/60).toFixed(1)} <small>hr</small></strong></div><div className="stat"><span>AWAITING REVIEW</span><strong>{p.pending.toString().padStart(2,'0')}</strong></div></div><div className="familyGrid"><section className="card"><div className="formHeader"><h2>Practice history</h2><span>{state.logs.length} ENTRIES</span></div>{state.logs.length===0?<div className="empty">No drives recorded yet. Start with a short supervised session, then log it once parked.</div>:<div className="history">{state.logs.map(l=><div className="historyItem" key={l.id}><div><strong>{l.skill}</strong><span>{l.date} · {l.minutes} min · {l.supervisor}{l.night?' · Night':''}</span>{l.note&&<p>{l.note}</p>}</div><div className="historyAction"><span className={l.status==='verified'?'verified':'pending'}>{l.status==='verified'?'Verified':'Pending'}</span>{l.status==='pending'&&role==='parent'&&<button disabled={busy} onClick={()=>act({action:'verify',id:l.id})}>Verify entry →</button>}</div></div>)}</div>}</section><section className="card goalCard"><div className="formHeader"><h2>Family goal</h2><span>OPTIONAL</span></div><p>Set a practice target for your family. Local licensing minimums may differ.</p><label>Goal in hours<input type="number" min="1" max="200" value={goal} onChange={e=>setGoal(Number(e.target.value))}/></label><button disabled={busy||role!=='parent'} className="secondary" onClick={()=>act({action:'goal',hours:Number(goal)})}>Update goal</button>{role==='teen'&&<small>A parent can update this goal.</small>}<div className="goalBar"><div className="bar"><i style={{width:`${p.percent}%`}}/></div><span>{p.percent}% of family goal</span></div></section></div></div>}
 </>}</main></div>
}
