'use client';
import {useEffect,useState} from 'react';

type Policy={policyId:string;carrierId:string;externalPolicyId:string;teenName:string;status:string;effectiveAt?:string;renewalAt?:string;cancellationAt?:string;coveredVehicles:Array<{year:number;make:string;model:string;vinLast4?:string}>;documents:Array<{label:string;available:boolean;externalUrl?:string}>;timeline:Array<{state:string;at:string;source:string}>;attention?:string};
type Dashboard={activeCount:number;attentionCount:number;disclaimer:string;policies:Policy[]};
type ValueDashboard={cumulativeRealizedAnnualizedCents:number;disclaimer:string;teens:Array<{teenId:string;teenName:string;currentMonthlyCents?:number;projectedMonthlyCents?:number;activeMonthlyCents?:number;projectedAnnualizedValueCents?:number;realizedAnnualizedValueCents?:number;carrierDiscounts:Array<{label:string;amountCents?:number}>}>;milestones:Array<{id:string;label:string;amountCents:number;achievedAt:string}>};
type Notice={id:string;title:string;message:string;priority:'normal'|'high';status:string;cta:{label:string;href:string}};
const money=(c?:number)=>typeof c==='number'?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(c/100):'Not available';

export default function ParentInsurancePage(){
 const [data,setData]=useState<Dashboard|null>(null);const [value,setValue]=useState<ValueDashboard|null>(null);const [notices,setNotices]=useState<Notice[]>([]);const [error,setError]=useState('');const [missing,setMissing]=useState(false);
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get('householdId')||'';if(!id){setMissing(true);return}fetch('/api/insurance/dashboard?householdId='+encodeURIComponent(id),{cache:'no-store'}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error||'Unable to load insurance.');return b as Dashboard}).then(setData).catch(e=>setError(e instanceof Error?e.message:'Unable to load insurance.'));fetch('/api/insurance/value-dashboard?householdId='+encodeURIComponent(id),{cache:'no-store'}).then(async r=>r.ok?await r.json():null).then(setValue).catch(()=>undefined);fetch('/api/insurance/notifications?householdId='+encodeURIComponent(id),{cache:'no-store'}).then(async r=>r.ok?await r.json():null).then(b=>setNotices((b?.notifications||[]).filter((n:Notice)=>n.status==='unread'))).catch(()=>undefined)},[]);
 if(missing)return <main className="shell"><h1>Insurance</h1><p>Select a household from your parent dashboard to view coverage.</p></main>;
 if(error)return <main className="shell"><h1>Insurance</h1><p role="alert">{error}</p></main>;
 if(!data)return <main className="shell"><h1>Insurance</h1><p>Loading carrier-confirmed policy status...</p></main>;
 return <main className="shell"><header><p className="eyebrow">Parent insurance center</p><h1>Coverage and policy lifecycle</h1><p>{data.activeCount} active · {data.attentionCount} needing attention</p></header>{notices.length?<section className="card"><h2>Insurance actions</h2>{notices.map(n=><div key={n.id}><p><strong>{n.priority==='high'?'Action needed: ':''}{n.title}</strong><br/>{n.message}</p><a href={n.cta.href}>{n.cta.label}</a></div>)}</section>:null}
 {value?<section className="card"><h2>Insurance value</h2><div className="grid"><p><b>Household annualized realized value</b><br/>{money(value.cumulativeRealizedAnnualizedCents)}</p><p><b>Evidence milestones</b><br/>{value.milestones.length}</p></div>{value.teens.map(t=><div key={t.teenId}><h3>{t.teenName}</h3><div className="grid"><p><b>Current monthly baseline</b><br/>{money(t.currentMonthlyCents)}</p><p><b>Projected monthly quote</b><br/>{money(t.projectedMonthlyCents)}</p><p><b>Carrier-confirmed active monthly</b><br/>{money(t.activeMonthlyCents)}</p><p><b>Projected annualized value</b><br/>{money(t.projectedAnnualizedValueCents)}</p><p><b>Realized annualized value</b><br/>{money(t.realizedAnnualizedValueCents)}</p></div>{t.carrierDiscounts.length?<p><b>Carrier-verified discounts:</b> {t.carrierDiscounts.map(d=>d.label+(d.amountCents?' ('+money(d.amountCents)+')':'')).join(', ')}</p>:null}</div>)}{value.milestones.length?<details><summary>Savings milestones</summary><ul>{value.milestones.map(m=><li key={m.id}>{m.label} · {money(m.amountCents)} · {m.achievedAt}</li>)}</ul></details>:null}<p className="fine">{value.disclaimer}</p></section>:null}
 {data.policies.length===0?<section className="card"><h2>No carrier-confirmed policy yet</h2><p>Complete quote comparison and carrier binding first.</p></section>:null}
 {data.policies.map(p=><article className="card" key={p.policyId}><div className="split"><div><h2>{p.teenName}</h2><p>Carrier: {p.carrierId}</p><p>Policy: {p.externalPolicyId}</p></div><strong>{p.status.replaceAll('_',' ')}</strong></div>
 {p.attention?<p role="alert"><strong>{p.attention}</strong></p>:null}
 <div className="grid"><p><b>Effective</b><br/>{p.effectiveAt||'Carrier not provided'}</p><p><b>Renewal</b><br/>{p.renewalAt||'Carrier not provided'}</p><p><b>Cancellation</b><br/>{p.cancellationAt||'None reported'}</p></div>
 <h3>Covered vehicles</h3>{p.coveredVehicles.length?p.coveredVehicles.map((v,i)=><p key={i}>{v.year} {v.make} {v.model}{v.vinLast4?' · VIN ••••'+v.vinLast4:''}</p>):<p>Vehicle details unavailable.</p>}
 <h3>Carrier documents</h3><ul>{p.documents.map((d,i)=><li key={i}>{d.available&&d.externalUrl?<a href={d.externalUrl} target="_blank" rel="noreferrer">{d.label}</a>:d.label+' — not yet available'}</li>)}</ul>
 <details><summary>Policy timeline</summary><ol>{p.timeline.map((t,i)=><li key={i}>{t.at} · {t.state} · {t.source}</li>)}</ol></details></article>)}
 <p className="fine">{data.disclaimer}</p>
 <style jsx>{`.shell{max-width:960px;margin:40px auto;padding:0 20px}.eyebrow{text-transform:uppercase;letter-spacing:1px;font-size:12px}.card{border:1px solid #d9d9d9;border-radius:16px;padding:22px;margin:18px 0}.split{display:flex;justify-content:space-between;gap:20px;flex-wrap:wrap}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px}.fine{font-size:13px}`}</style></main>
}