import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {mkdtempSync,rmSync,existsSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {register} from '../platform/auth';
import {execute} from '../platform/service';
import {all,put,db,closeDatabases} from '../platform/db';
import type {User,Profile,Relationship} from '../platform/types';
import {executeIntelligence,readIntelligence} from './intelligence-service';
import {hazardScenes,assessHazard} from './core/hazards';
import {concepts,challenges,jurisdictionPack} from './content';
import {available,type ContentStatus} from './governance';
import {chooseScout,keepRecommendation} from './scout';
import {validateIntelligence} from './intelligence-validation';
import type {PracticeSession,Recommendation} from './intelligence-types';
import type {LearningEvidence} from './types';
import {migrateIntelligence} from '../platform/migrations/003-intelligence';
let dir:string;
beforeEach(()=>{dir=mkdtempSync(join(tmpdir(),'intelligence-'));process.env.TEENSURANCE_DB_PATH=join(dir,'db.sqlite');process.env.ROADREADY_LEARNING_ENABLED='true'});
afterEach(()=>{vi.useRealTimers();closeDatabases();delete process.env.TEENSURANCE_DB_PATH;delete process.env.ROADREADY_LEARNING_ENABLED;rmSync(dir,{recursive:true,force:true})});
function setup(){const parent=register('p@example.test','long-password-123','Parent');const teen=register('t@example.test','long-password-123','Teen');const other=register('o@example.test','long-password-123','Other');const h=execute(parent,{action:'household.create',name:'Family',adultAttestation:true},randomUUID()) as {result:{id:string}};const householdId=h.result.id;const invite=execute(parent,{action:'invite.create',householdId,role:'teen'},randomUUID()) as {result:{token:string}};execute(teen,{action:'invite.accept',token:invite.result.token},randomUUID());execute(teen,{action:'profile.save',householdId,teenId:teen.id,name:'Teen',birthDate:'2010-01-01',jurisdiction:'TX',stage:'permit',goalMinutes:1800,permitDate:'2025-01-01',suspensionDays:0},randomUUID());execute(parent,{action:'consent.set',householdId,teenId:teen.id,granted:true},randomUUID());return {parent,teen,other,householdId}}

function run(f:ReturnType<typeof setup>,action:Record<string,unknown>,user:User=f.teen,key=randomUUID()){return executeIntelligence(user,{householdId:f.householdId,teenId:f.teen.id,context:'AT_HOME',...action},key)}
function started(f:ReturnType<typeof setup>,kind:string,itemId?:string){return (run(f,{action:'start',kind,itemId}) as {result:PracticeSession}).result}
const scene=hazardScenes[0];
it('validates all governed concepts, challenges and twelve original hazard assets',()=>{expect(hazardScenes).toHaveLength(12);expect(validateIntelligence(path=>existsSync(join(process.cwd(),'public',path)))).toEqual([])});
it.each(['draft','review','approved','retired'] as ContentStatus[])('%s content is never learner visible',status=>{expect(available([{...concepts[0],status}],'US-TX')).toEqual([])});
it('published metadata survives resolution and Texas never leaks to other states',()=>{expect(available([concepts[0]],'US-TX')[0]).toMatchObject({source:concepts[0].source,version:concepts[0].version});expect(jurisdictionPack('US-CA').concepts).toEqual([])});
it('assesses incomplete, wrong and correct hazard responses without timing scores',()=>{expect(assessHazard(scene,[],scene.responseId)).toBe(false);expect(assessHazard(scene,['background'],scene.responseId)).toBe(false);expect(assessHazard(scene,scene.targetIds,'invalid')).toBe(false);expect(assessHazard(scene,scene.targetIds,scene.responseId)).toBe(true)});
it('saves wrong hazard evidence, explanation, mastery and persistence',()=>{const f=setup();const s=started(f,'hazard',scene.id);const r=run(f,{action:'answer',sessionId:s.id,itemId:scene.id,targets:['background'],answerId:scene.responseId}) as {result:{correct:boolean;explanation:string}};expect(r.result.correct).toBe(false);expect(r.result.explanation).toBe(scene.explanation);closeDatabases();const d=readIntelligence(f.teen,f.householdId,f.teen.id).data!;expect(d.hazardPassport[0].state).toBe('practicing');expect(d.recentEvidence).toHaveLength(1);expect(d.recentEvidence[0].selectedTargets).toEqual(['background'])});
it('valid hazard responses introduce knowledge but repeated same scene cannot fake mastery',()=>{const f=setup();for(let i=0;i<3;i++){const s=started(f,'hazard',scene.id);expect(run(f,{action:'answer',sessionId:s.id,itemId:scene.id,targets:scene.targetIds,answerId:scene.responseId}).status).toBe(200)}expect(readIntelligence(f.teen,f.householdId,f.teen.id).data!.hazardPassport[0]).toMatchObject({state:'introduced',qualifyingObservations:1})});
it('permit practice persists missed concepts and leaves Passport evidence untouched',()=>{const f=setup();const s=started(f,'permit');for(const id of s.itemIds){const q=challenges.find(q=>q.id===id)!;expect(run(f,{action:'answer',sessionId:s.id,itemId:id,answerId:q.options.find(o=>o.id!==q.answerId)!.id}).status).toBe(200)}closeDatabases();const d=readIntelligence(f.teen,f.householdId,f.teen.id).data!;expect(d.permit.completed).toBe(1);expect(d.permit.missed.length).toBeGreaterThan(0);expect(all('roadready_attempt')).toEqual([]);expect(all('roadready_mastery')).toEqual([]);const next=started(f,'permit');expect(next.itemIds[0]).not.toBe(s.itemIds[0])});
it('non-Texas users receive explicit fallback, core hazards and no permit questions',()=>{const f=setup();const p=all<Profile>('profile')[0];put('profile',{...p,jurisdiction:'CA'});const d=readIntelligence(f.teen,f.householdId,f.teen.id).data!;expect(d.fallback).toContain('not yet available');expect(d.hazards).toHaveLength(12);expect(run(f,{action:'start',kind:'permit'}).status).toBe(409);expect(run(f,{action:'start',kind:'review',itemId:'US-TX:stop'}).status).toBe(409)});
it('unpublishing an active question blocks submission without writing evidence',()=>{const f=setup();const s=started(f,'review',concepts[0].id);const q=challenges.find(q=>q.id===s.itemIds[0])!;const c=concepts.find(c=>c.id===q.conceptId)!;const old=c.status;try{c.status='retired';expect(run(f,{action:'answer',sessionId:s.id,itemId:q.id,answerId:q.answerId}).status).toBe(409);expect(all('roadready_attempt')).toEqual([])}finally{c.status=old}});
it('unpublishing a hazard blocks active reads and writes',()=>{const f=setup();const s=started(f,'hazard',scene.id);const old=scene.status;try{scene.status='draft';expect(readIntelligence(f.teen,f.householdId,f.teen.id).data!.sessions[0].item).toBeNull();expect(run(f,{action:'answer',sessionId:s.id,itemId:scene.id,targets:scene.targetIds,answerId:scene.responseId}).status).toBe(409)}finally{scene.status=old}});
it('guardian activity preserves learner history and creates separate provenance',()=>{const f=setup();for(let i=0;i<3;i++)put<LearningEvidence>('roadready_attempt',{id:randomUUID(),householdId:f.householdId,ownerId:f.teen.id,teenId:f.teen.id,conceptId:'US-TX:stop',sessionId:randomUUID(),challengeId:`US-TX:stop:v${i+1}`,answerId:'a',correct:true,kind:'learning',at:new Date(Date.now()-(4-i)*86400000).toISOString(),contentVersion:concepts[0].version});const before=all('roadready_attempt');const a=run(f,{action:'coach_start',conceptId:'US-TX:stop'},f.parent) as {result:{id:string}};const r=run(f,{action:'coach_complete',activityId:a.result.id,completed:true},f.parent) as {result:{mastery:{state:string}}};expect(r.result.mastery.state).toBe('reinforced');expect(all('roadready_attempt')).toEqual(before);expect(all('roadready_guardian')).toHaveLength(1);expect(run(f,{action:'coach_complete',activityId:a.result.id,completed:true},f.parent).status).toBe(409)});
it.each(['coach_start','coach_complete'])('teen cannot forge %s',action=>{const f=setup();expect(run(f,{action,...(action==='coach_start'?{conceptId:'US-TX:stop'}:{activityId:randomUUID(),completed:true})}).status).toBe(403)});
it('unrelated callers and sibling IDs are denied before private records',()=>{const f=setup();expect(readIntelligence(f.other,f.householdId,f.teen.id).status).toBe(403);expect(readIntelligence(f.teen,f.householdId,f.other.id).status).toBe(403);expect(run(f,{action:'start',kind:'hazard'},f.other).status).toBe(403)});
it.each(['role','guardianId','userId'])('rejects injected %s',field=>{const f=setup();expect(run(f,{action:'start',kind:'hazard',[field]:'guardian'}).status).toBe(400)});
it('session ID tampering and idempotency conflict cannot alter evidence',()=>{const f=setup();const s=started(f,'hazard');const key=randomUUID();const c={action:'answer',sessionId:s.id,itemId:scene.id,targets:scene.targetIds,answerId:scene.responseId};expect(run(f,{...c,sessionId:randomUUID()}).status).toBe(404);expect(run(f,c,f.teen,key).status).toBe(200);expect(run(f,c,f.teen,key).status).toBe(200);expect(all('roadready_attempt')).toHaveLength(1);expect(run(f,{...c,answerId:'other'},f.teen,key).status).toBe(409)});
it('consent, revoked relationship, active driving and feature flag fail closed',()=>{const f=setup();const p=all<Profile>('profile')[0];put('profile',{...p,consent:false});expect(readIntelligence(f.teen,f.householdId,f.teen.id).status).toBe(403);put('profile',p);const link=all<Relationship>('relationship')[0];put('relationship',{...link,active:false});expect(readIntelligence(f.parent,f.householdId,f.teen.id).status).toBe(403);put('relationship',link);execute(f.teen,{action:'drive.start',householdId:f.householdId,teenId:f.teen.id,supervisorId:f.parent.id,skill:'Parking',supervisorEligible:true},randomUUID());expect(run(f,{action:'start',kind:'hazard'}).status).toBe(403);process.env.ROADREADY_LEARNING_ENABLED='false';expect(readIntelligence(f.teen,f.householdId,f.teen.id).status).toBe(404)});
it.each(['IN_DRIVE','reaction_time_score','hazard_leaderboard','driving_risk_score'])('denies prohibited context or mechanism %s',value=>{const f=setup();expect(run(f,value==='IN_DRIVE'?{action:'start',kind:'hazard',context:value}:{action:value}).status).toBe(400)});
it('migration is idempotent and permit evidence is append only',()=>{const f=setup();const s=started(f,'permit');const q=challenges.find(q=>q.id===s.itemIds[0])!;run(f,{action:'answer',sessionId:s.id,itemId:q.id,answerId:q.answerId});migrateIntelligence(db());expect(()=>db().exec("DELETE FROM records WHERE kind='permit_attempt'")).toThrow('append only');expect(()=>db().exec("UPDATE records SET payload='{}' WHERE kind='permit_attempt'")).toThrow('append only')});
function scoutInput(){return {concepts:concepts.slice(0,3),hazards:hazardScenes,mastery:concepts.slice(0,3).map(c=>({conceptId:c.id,state:'not_started' as const,qualifyingObservations:0,evidenceIds:[]})),evidence:[] as LearningEvidence[],sessions:[] as PracticeSession[],guardian:false,now:new Date().toISOString()}}
function miss(id:string):LearningEvidence{return {id:randomUUID(),householdId:'h',ownerId:'t',teenId:'t',conceptId:id,sessionId:randomUUID(),challengeId:'q',answerId:'x',correct:false,at:new Date().toISOString(),kind:'learning',contentVersion:'v1'}}
it('single miss does not trigger targeted review; repeated misses do',()=>{const i=scoutInput();i.evidence=[miss(concepts[0].id)];expect(chooseScout(i).type).not.toBe('retry_weak_concept');i.evidence.push(miss(concepts[0].id));expect(chooseScout(i)).toMatchObject({type:'retry_weak_concept',conceptId:concepts[0].id,priority:2});expect(chooseScout(i).reason).toContain('2 recent')});
it('safety supersedes optional review and active sessions resume before category gaps',()=>{const i=scoutInput();expect(chooseScout({...i,safetyReason:'Park first'}).priority).toBe(0);i.sessions=[{id:'s',householdId:'h',ownerId:'t',teenId:'t',kind:'permit',jurisdiction:'US-TX',itemIds:[],cursor:0,startedAt:i.now}];expect(chooseScout(i).type).toBe('resume_session')});
it('hazard weaknesses and demonstrated guardian concepts select appropriate actions',()=>{const i=scoutInput();i.mastery.push({conceptId:scene.conceptId,state:'not_started',qualifyingObservations:0,evidenceIds:[]});i.evidence=[miss(scene.conceptId),miss(scene.conceptId)];expect(chooseScout(i).type).toBe('start_hazard_scene');expect(chooseScout({...i,guardian:true,mastery:[{conceptId:concepts[0].id,state:'demonstrated',qualifyingObservations:3,evidenceIds:[]}]}).type).toBe('guardian_reinforcement')});
it('recommendations remain stable, dismiss cleanly and targeted completion advances',()=>{const f=setup();const first=readIntelligence(f.teen,f.householdId,f.teen.id).data!.recommendation;expect(readIntelligence(f.teen,f.householdId,f.teen.id).data!.recommendation.id).toBe(first.id);expect(run(f,{action:'dismiss',recommendationId:first.id}).status).toBe(200);const next=readIntelligence(f.teen,f.householdId,f.teen.id).data!.recommendation;expect(next.conceptId).not.toBe(first.conceptId);const s=(run(f,{action:'start',kind:'review',itemId:next.conceptId,recommendationId:next.id}) as {result:PracticeSession}).result;expect(s.itemIds).toHaveLength(3);for(const id of s.itemIds){const q=challenges.find(q=>q.id===id)!;run(f,{action:'answer',sessionId:s.id,itemId:id,answerId:q.answerId})}expect(all<Recommendation>('scout_plan').find(r=>r.id===next.id)!.status).toBe('completed');expect(readIntelligence(f.teen,f.householdId,f.teen.id).data!.recommendation.id).not.toBe(next.id)});
it('higher priority evidence supersedes a persisted optional recommendation',()=>{const i=scoutInput();const choice=chooseScout(i);const previous={...choice,priority:8,status:'recommended',expiresAt:new Date(Date.now()+10000).toISOString()} as Recommendation;expect(keepRecommendation(previous,{...choice,priority:2},i.now)).toBe(false);expect(keepRecommendation(previous,choice,'9999-01-01')).toBe(false)});

it('three distinct hazard scenes demonstrate and same-timestamp guardian evidence reinforces deterministically',()=>{const f=setup();vi.useFakeTimers();for(let i=0;i<3;i++){vi.setSystemTime(new Date(Date.UTC(2026,8,20+i)));const h=hazardScenes[i];const s=started(f,'hazard',h.id);expect(run(f,{action:'answer',sessionId:s.id,itemId:h.id,targets:h.targetIds,answerId:h.responseId}).status).toBe(200)}expect(readIntelligence(f.teen,f.householdId,f.teen.id).data!.hazardPassport[0].state).toBe('demonstrated');const a=run(f,{action:'coach_start',conceptId:scene.conceptId,context:'POST_DRIVE'},f.parent) as {result:{id:string}};expect(run(f,{action:'coach_complete',activityId:a.result.id,completed:true},f.parent).status).toBe(200);expect(readIntelligence(f.teen,f.householdId,f.teen.id).data!.hazardPassport[0].state).toBe('reinforced');expect(all<{context:string}>('roadready_guardian')[0].context).toBe('POST_DRIVE')});
it('a successful retry stops the repeated-miss trigger',()=>{const i=scoutInput();const a=miss(concepts[0].id);a.at='2026-09-20T12:00:00.000Z';i.evidence=[a,{...a,id:'second'},{...a,id:'retry',correct:true,at:'2026-09-21T12:00:00.000Z'}];expect(chooseScout(i).type).not.toBe('retry_weak_concept')});

it('retired recommendation content is replaced and unavailable sessions cannot trap a learner',()=>{const f=setup();const r=readIntelligence(f.teen,f.householdId,f.teen.id).data!.recommendation;const c=concepts.find(c=>c.id===r.conceptId)!;const old=c.status;try{started(f,'review',c.id);c.status='retired';const d=readIntelligence(f.teen,f.householdId,f.teen.id).data!;expect(d.recommendation.conceptId).not.toBe(c.id);const replacement=started(f,'review',concepts.find(x=>x.status==='published')!.id);expect(replacement.itemIds.length).toBe(3)}finally{c.status=old}});
