import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {existsSync,mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {randomUUID} from 'node:crypto';
import {concepts,challenges,jurisdictionPack,validateContent} from './content';
import {mastery,learningPolicy,prohibitedActions,observationGapMs} from './rules';
import {executeRoadReady,readRoadReady} from './service';
import {scoutContract} from './agent';
import {all,closeDatabases,db,put} from '../platform/db';
import {register} from '../platform/auth';
import {execute} from '../platform/service';
import type {User,Profile,Drive,Relationship} from '../platform/types';
import type {LearningEvidence,GuardianReinforcement,LearningSession} from './types';
const conceptId='US-TX:stop';
const observation=(day:number,variant=day,correct=true):LearningEvidence=>({id:`e${day}-${variant}`,householdId:'h',ownerId:'t',teenId:'t',conceptId,sessionId:`s${day}`,challengeId:`q${variant}`,answerId:'a',correct,at:new Date(Date.UTC(2026,0,day)).toISOString(),kind:'learning',contentVersion:'v1'});
describe('RoadReady content and deterministic safety',()=>{
 it('validates the complete jurisdiction pack and every on-disk asset',()=>{expect(concepts.length).toBeGreaterThanOrEqual(50);expect(concepts.length).toBeLessThanOrEqual(75);expect(validateContent(concepts,challenges,p=>existsSync(join(process.cwd(),'public',p)))).toEqual([]);expect(jurisdictionPack('US-CA').concepts).toEqual([]);expect(new Set(challenges.map(c=>c.mode)).size).toBe(5)});
 it('fails duplicate ids, missing jurisdiction/source/explanation/assets and invalid challenge references/answers',()=>{expect(validateContent([concepts[0],{...concepts[0],jurisdiction:'',explanation:'',sourceUrl:''}],[{...challenges[0],conceptId:'missing',answerId:'missing',explanation:''}],()=>false).length).toBeGreaterThanOrEqual(7)});
 it.each(prohibitedActions)('GUARD denies %s',action=>expect(learningPolicy(action,false).decision).toBe('DENY'));
 it('defers all learning during driving',()=>{for(const action of ['read','start','answer','reinforce'])expect(learningPolicy(action,true).decision).toBe('DEFER')});
 it('Scout provides the complete machine-readable contract',()=>{expect(Object.keys(scoutContract)).toEqual(expect.arrayContaining(['agent_id','objective','minor_data_permissions','handoff_targets','evidence_requirements','safety_classification']));expect(scoutContract.prohibited_actions).toContain('insurance_risk_score')});
 it('one correct answer and rapid/replayed variants cannot establish mastery',()=>{expect(mastery(conceptId,[observation(1)],[]).state).toBe('introduced');expect(mastery(conceptId,[observation(1,1),observation(1,2),observation(1,3)],[]).state).toBe('introduced');expect(mastery(conceptId,[observation(1,1),observation(2,1),observation(3,1)],[]).qualifyingObservations).toBe(1)});
 it('requires three separate qualifying observations, then later evidence reinforces',()=>{const e=[observation(1),observation(2),observation(3)];expect(mastery(conceptId,e,[]).state).toBe('demonstrated');expect(mastery(conceptId,[...e,observation(4)],[]).state).toBe('reinforced');expect(mastery(conceptId,[...e,observation(5,5,false)],[])).toMatchObject({state:'practicing',qualifyingObservations:0,retryAt:new Date(Date.parse(observation(5).at)+observationGapMs).toISOString()})});
 it('guardian evidence reinforces only qualifying learning and preserves history',()=>{const e=[observation(1),observation(2),observation(3)];const before=JSON.stringify(e);const g:GuardianReinforcement={id:'g',householdId:'h',ownerId:'p',teenId:'t',conceptId,at:observation(4).at,kind:'guardian',completed:true,context:'PARKED',guardianId:'p'};expect(mastery(conceptId,e,[g]).state).toBe('reinforced');expect(mastery(conceptId,[],[g]).state).toBe('introduced');expect(JSON.stringify(e)).toBe(before)});
});
let dir:string;
beforeEach(()=>{dir=mkdtempSync(join(tmpdir(),'roadready-'));process.env.TEENSURANCE_DB_PATH=join(dir,'test.sqlite');process.env.ROADREADY_LEARNING_ENABLED='true'});
afterEach(()=>{vi.useRealTimers();closeDatabases();delete process.env.TEENSURANCE_DB_PATH;delete process.env.ROADREADY_LEARNING_ENABLED;rmSync(dir,{recursive:true,force:true})});
function setup(){const parent=register('p@example.test','long-password-123','Parent');const teen=register('t@example.test','long-password-123','Teen');const other=register('o@example.test','long-password-123','Other');const h=execute(parent,{action:'household.create',name:'Family',adultAttestation:true},randomUUID()) as {result:{id:string}};const householdId=h.result.id;const invite=execute(parent,{action:'invite.create',householdId,role:'teen'},randomUUID()) as {result:{token:string}};execute(teen,{action:'invite.accept',token:invite.result.token},randomUUID());execute(teen,{action:'profile.save',householdId,teenId:teen.id,name:'Teen',birthDate:'2010-01-01',jurisdiction:'TX',stage:'permit',goalMinutes:1800,permitDate:'2025-01-01',suspensionDays:0},randomUUID());execute(parent,{action:'consent.set',householdId,teenId:teen.id,granted:true},randomUUID());return {parent,teen,other,householdId}}
function run(user:User,householdId:string,teenId:string,action:Record<string,unknown>,key=randomUUID()){
 const q=challenges.find(q=>q.id===action.challengeId);
 const answerId=action.answerId==='meaning'?q?.answerId:action.answerId==='misconception'?q?.options.find(o=>o.id!==q.answerId)?.id:action.answerId;
 return executeRoadReady(user,{householdId,teenId,context:'PARKED',...action,...(answerId?{answerId}:{})},key);
}
describe('RoadReady service and real SQLite security',()=>{
 it('persists answers, explanations, sessions, retries, recommendations, Passport links and survives reopen',()=>{const {teen,householdId}=setup();const started=run(teen,householdId,teen.id,{action:'start',mode:'Sign Snap',conceptId}) as {result:LearningSession};const wrong=run(teen,householdId,teen.id,{action:'answer',sessionId:started.result.id,challengeId:started.result.challengeIds[0],answerId:'misconception'});expect(wrong.status).toBe(200);closeDatabases();const snapshot=readRoadReady(teen,householdId,teen.id);expect(snapshot.data?.mastery.find(m=>m.conceptId===conceptId)?.state).toBe('practicing');expect(snapshot.data?.passport.find(m=>m.conceptId===conceptId)?.evidenceIds).toHaveLength(1);const next=run(teen,householdId,teen.id,{action:'start',mode:'Sign Snap',conceptId}) as {result:LearningSession};expect(next.result.challengeIds[0]).not.toBe(started.result.challengeIds[0]);expect(all('roadready_mastery')).toHaveLength(1);expect(all('roadready_recommendation')).toHaveLength(1)});
 it('denies cross-household access, unrelated guardians, teens forging guardian evidence and records denials',()=>{const {parent,teen,other,householdId}=setup();expect(readRoadReady(teen,householdId,teen.id).status).toBe(200);expect(readRoadReady(parent,householdId,teen.id).status).toBe(200);expect(readRoadReady(other,householdId,teen.id).status).toBe(403);expect(readRoadReady(teen,householdId,other.id).status).toBe(403);expect(run(teen,householdId,teen.id,{action:'reinforce',conceptId,completed:true}).status).toBe(403);expect(run(other,householdId,teen.id,{action:'reinforce',conceptId,completed:true}).status).toBe(403);expect(all('roadready_guardian')).toEqual([]);expect(db().prepare("SELECT * FROM audit WHERE decision='DENY'").all().length).toBeGreaterThanOrEqual(4)});
 it('enforces consent, revoked relationships, adult sharing, jurisdiction and feature flag',()=>{const {parent,teen,householdId}=setup();const p=all<Profile>('profile')[0];put('profile',{...p,consent:false});expect(readRoadReady(teen,householdId,teen.id).status).toBe(403);put('profile',{...p,birthDate:'2000-01-01',adultSharing:false});expect(readRoadReady(parent,householdId,teen.id).status).toBe(403);put('profile',{...p,jurisdiction:'CA'});expect(readRoadReady(teen,householdId,teen.id).status).toBe(409);put('profile',p);const relation=all<Relationship>('relationship')[0];put('relationship',{...relation,active:false});expect(readRoadReady(parent,householdId,teen.id).status).toBe(403);process.env.ROADREADY_LEARNING_ENABLED='false';expect(readRoadReady(teen,householdId,teen.id).status).toBe(404)});
 it('blocks learning when the teen has an active drive, including guardian requests',()=>{const {parent,teen,householdId}=setup();const drive=execute(teen,{action:'drive.start',householdId,teenId:teen.id,supervisorId:parent.id,skill:'Parking',supervisorEligible:true},randomUUID()) as {result:Drive};expect(drive.result.status).toBe('active');expect(readRoadReady(teen,householdId,teen.id).status).toBe(403);expect(run(parent,householdId,teen.id,{action:'reinforce',conceptId,completed:true}).status).toBe(403)});
 it('rejects forged answers, repeated submissions and context spoofing',()=>{const {teen,householdId}=setup();const c={action:'start',mode:'Sign Snap',conceptId};const key=randomUUID();const s=run(teen,householdId,teen.id,c,key) as {result:LearningSession};expect(run(teen,householdId,teen.id,c,key)).toEqual(s);expect(run(teen,householdId,teen.id,{...c,mode:'Signal Sense'},key).status).toBe(409);const answer={action:'answer',sessionId:s.result.id,challengeId:s.result.challengeIds[0],answerId:'meaning'};expect(run(teen,householdId,teen.id,{...answer,answerId:'forged'}).status).toBe(409);expect(run(teen,householdId,teen.id,{...answer,correct:true}).status).toBe(400);expect(run(teen,householdId,teen.id,{...answer,context:'DRIVING'}).status).toBe(400);expect(run(teen,householdId,teen.id,answer).status).toBe(200);expect(run(teen,householdId,teen.id,answer).status).toBe(409);expect(all('roadready_attempt')).toHaveLength(1)});
 it('database triggers prohibit mutation/deletion of both evidence kinds',()=>{const {parent,teen,householdId}=setup();readRoadReady(teen,householdId,teen.id);run(parent,householdId,teen.id,{action:'reinforce',conceptId,completed:true});put('roadready_attempt',{...observation(1),householdId,ownerId:teen.id,teenId:teen.id});for(const kind of ['roadready_attempt','roadready_guardian']){expect(()=>db().prepare('DELETE FROM records WHERE kind=?').run(kind)).toThrow('append only');expect(()=>db().prepare("UPDATE records SET payload='{}' WHERE kind=?").run(kind)).toThrow('append only')}});
 it('end-to-end distinct days demonstrate, guardian reinforces with separate evidence',()=>{vi.useFakeTimers();const {parent,teen,householdId}=setup();for(let day=1;day<=3;day++){vi.setSystemTime(new Date(Date.UTC(2026,8,day)));const s=run(teen,householdId,teen.id,{action:'start',mode:'Sign Snap',conceptId}) as {result:LearningSession};expect(run(teen,householdId,teen.id,{action:'answer',sessionId:s.result.id,challengeId:s.result.challengeIds[0],answerId:'meaning'}).status).toBe(200)}expect(readRoadReady(teen,householdId,teen.id).data?.mastery.find(m=>m.conceptId===conceptId)?.state).toBe('demonstrated');vi.setSystemTime(new Date(Date.UTC(2026,8,4)));expect(run(parent,householdId,teen.id,{action:'reinforce',conceptId,completed:true}).status).toBe(200);expect(readRoadReady(teen,householdId,teen.id).data?.mastery.find(m=>m.conceptId===conceptId)?.state).toBe('reinforced');expect(all('roadready_attempt')).toHaveLength(3);expect(all('roadready_guardian')).toHaveLength(1)});
});
