import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {existsSync,mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {randomUUID} from 'node:crypto';
import {concepts,challenges,jurisdictionPack,validateContent} from './content';
import {mastery,learningPolicy,prohibitedActions,observationGapMs} from './rules';
import {executeRoadReady,readRoadReady} from './service';
import {scoutContract} from './agent';
import {all,closeDatabases,db,put} from '../platform/db';
import {register} from '../platform/auth';
import {execute} from '../platform/service';
import type {User,Profile,Drive,Relationship} from '../platform/types';
import type {LearningEvidence,GuardianReinforcement,LearningSession} from './types';
const conceptId='US-TX:stop';
const observation=(day:number,variant=day,correct=true):LearningEvidence=>({id:`e${day}-${variant}`,householdId:'h',ownerId:'t',teenId:'t',conceptId,sessionId:`s${day}`,challengeId:`q${variant}`,answerId:'a',correct,at:new Date(Date.UTC(2026,0,day)).toISOString(),kind:'learning',contentVersion:'v1'});
describe('RoadReady content and deterministic safety',()=>{
 it('validates the complete jurisdiction pack and every on-disk asset',()=>{expect(concepts.length).toBeGreaterThanOrEqual(50);expect(concepts.length).toBeLessThanOrEqual(75);expect(validateContent(concepts,challenges,p=>existsSync(join(process.cwd(),'public',p)))).toEqual([]);expect(jurisdictionPack('US-CA').concepts).toEqual([]);expect(new Set(challenges.map(c=>c.mode)).size).toBe(5)});
 it('fails duplicate ids, missing jurisdiction/source/explanation/assets and invalid challenge references/answers',()=>{expect(validateContent([concepts[0],{...concepts[0],jurisdiction:'',explanation:'',sourceUrl:''}],[{...challenges[0],conceptId:'missing',answerId:'missing',explanation:''}],()=>false).length).toBeGreaterThanOrEqual(7)});
 it.each(prohibitedActions)('GUARD denies %s',action=>expect(learningPolicy(action,false).decision).toBe('DENY'));
 it('defers all learning during driving',()=>{for(const action of ['read','start','answer','reinforce'])expect(learningPolicy(action,true).decision).toBe('DEFER')});
 it('Scout provides the complete machine-readable contract',()=>{expect(Object.keys(scoutContract)).toEqual(expect.arrayContaining(['agent_id','objective','minor_data_permissions','handoff_targets','evidence_requirements','safety_classification']));expect(scoutContract.prohibited_actions).toContain('insurance_risk_score')});
 it('one correct answer and rapid/replayed variants cannot establish mastery',()=>{expect(mastery(conceptId,[observation(1)],[]).state).toBe('introduced');expect(mastery(conceptId,[observation(1,1),observation(1,2),observation(1,3)],[]).state).toBe('introduced');expect(mastery(conceptId,[observation(1,1),observation(2,1),observation(3,1)],[]).qualifyingObservations).toBe(1)});
 it('requires three separate qualifying observations, then later evidence reinforces',()=>{const e=[observation(1),observation(2),observation(3)];expect(mastery(conceptId,e,[]).state).toBe('demonstrated');expect(mastery(conceptId,[...e,observation(4)],[]).state).toBe('reinforced');expect(mastery(conceptId,[...e,observation(5,5,false)],[])).toMatchObject({state:'practicing',qualifyingObservations:0,retryAt:new Date(Date.parse(observation(5).at)+observationGapMs).toISOString()})});
 it('guardian evidence reinforces only qualifying learning and preserves history',()=>{const e=[observation(1),observation(2),observation(3)];const before=JSON.stringify(e);const g:GuardianReinforcement={id:'g',householdId:'h',ownerId:'p',teenId:'t',conceptId,at:observation(4).at,kind:'guardian',completed:true,context:'PARKED',guardianId:'p'};expect(mastery(conceptId,e,[g]).state).toBe('reinforced');expect(mastery(conceptId,[],[g]).state).toBe('introduced');expect(JSON.stringify(e)).toBe(before)});
});
let dir:string;
beforeEach(()=>{dir=mkdtempSync(join(tmpdir(),'roadready-'));process.env.TEENSURANCE_DB_PATH=join(dir,'test.sqlite');process.env.ROADREADY_LEARNING_ENABLED='true'});
afterEach(async ()=>{vi.useRealTimers();(await closeDatabases());delete process.env.TEENSURANCE_DB_PATH;delete process.env.ROADREADY_LEARNING_ENABLED;rmSync(dir,{recursive:true,force:true})});
async function setup(){const parent=(await register('p@example.test','long-password-123','Parent'));const teen=(await register('t@example.test','long-password-123','Teen'));const other=(await register('o@example.test','long-password-123','Other'));const h=(await execute(parent,{action:'household.create',name:'Family',adultAttestation:true},randomUUID())) as {result:{id:string}};const householdId=h.result.id;const invite=(await execute(parent,{action:'invite.create',householdId,role:'teen'},randomUUID())) as {result:{token:string}};(await execute(teen,{action:'invite.accept',token:invite.result.token},randomUUID()));(await execute(teen,{action:'profile.save',householdId,teenId:teen.id,name:'Teen',birthDate:'2010-01-01',jurisdiction:'TX',stage:'permit',goalMinutes:1800,permitDate:'2025-01-01',suspensionDays:0},randomUUID()));(await execute(parent,{action:'consent.set',householdId,teenId:teen.id,granted:true},randomUUID()));return {parent,teen,other,householdId}}
async function run(user:User,householdId:string,teenId:string,action:Record<string,unknown>,key=randomUUID()){
 const q=challenges.find(q=>q.id===action.challengeId);
 const answerId=action.answerId==='meaning'?q?.answerId:action.answerId==='misconception'?q?.options.find(o=>o.id!==q.answerId)?.id:action.answerId;
 return (await executeRoadReady(user,{householdId,teenId,context:'PARKED',...action,...(answerId?{answerId}:{})},key));
}
describe('RoadReady service and real SQLite security',()=>{
 it('persists answers, explanations, sessions, retries, recommendations, Passport links and survives reopen',async ()=>{const {teen,householdId}=(await setup());const started=(await run(teen,householdId,teen.id,{action:'start',mode:'Sign Snap',conceptId})) as {result:LearningSession};const wrong=(await run(teen,householdId,teen.id,{action:'answer',sessionId:started.result.id,challengeId:started.result.challengeIds[0],answerId:'misconception'}));expect(wrong.status).toBe(200);(await closeDatabases());const snapshot=(await readRoadReady(teen,householdId,teen.id));expect(snapshot.data?.mastery.find(m=>m.conceptId===conceptId)?.state).toBe('practicing');expect(snapshot.data?.passport.find(m=>m.conceptId===conceptId)?.evidenceIds).toHaveLength(1);const next=(await run(teen,householdId,teen.id,{action:'start',mode:'Sign Snap',conceptId})) as {result:LearningSession};expect(next.result.challengeIds[0]).not.toBe(started.result.challengeIds[0]);expect((await all('roadready_mastery'))).toHaveLength(1);expect((await all('roadready_recommendation'))).toHaveLength(1)});
 it('denies cross-household access, unrelated guardians, teens forging guardian evidence and records denials',async ()=>{const {parent,teen,other,householdId}=(await setup());expect((await readRoadReady(teen,householdId,teen.id)).status).toBe(200);expect((await readRoadReady(parent,householdId,teen.id)).status).toBe(200);expect((await readRoadReady(other,householdId,teen.id)).status).toBe(403);expect((await readRoadReady(teen,householdId,other.id)).status).toBe(403);expect((await run(teen,householdId,teen.id,{action:'reinforce',conceptId,completed:true})).status).toBe(403);expect((await run(other,householdId,teen.id,{action:'reinforce',conceptId,completed:true})).status).toBe(403);expect((await all('roadready_guardian'))).toEqual([]);expect((await db().prepare("SELECT * FROM audit WHERE decision='DENY'").all()).length).toBeGreaterThanOrEqual(4)});
 it('enforces consent, revoked relationships, adult sharing, jurisdiction and feature flag',async ()=>{const {parent,teen,householdId}=(await setup());const p=(await all<Profile>('profile'))[0];(await put('profile',{...p,consent:false}));expect((await readRoadReady(teen,householdId,teen.id)).status).toBe(403);(await put('profile',{...p,birthDate:'2000-01-01',adultSharing:false}));expect((await readRoadReady(parent,householdId,teen.id)).status).toBe(403);(await put('profile',{...p,jurisdiction:'CA'}));expect((await readRoadReady(teen,householdId,teen.id)).status).toBe(409);(await put('profile',p));const relation=(await all<Relationship>('relationship'))[0];(await put('relationship',{...relation,active:false}));expect((await readRoadReady(parent,householdId,teen.id)).status).toBe(403);process.env.ROADREADY_LEARNING_ENABLED='false';expect((await readRoadReady(teen,householdId,teen.id)).status).toBe(404)});
 it('blocks learning when the teen has an active drive, including guardian requests',async ()=>{const {parent,teen,householdId}=(await setup());const drive=(await execute(teen,{action:'drive.start',householdId,teenId:teen.id,supervisorId:parent.id,skill:'Parking',supervisorEligible:true},randomUUID())) as {result:Drive};expect(drive.result.status).toBe('active');expect((await readRoadReady(teen,householdId,teen.id)).status).toBe(403);expect((await run(parent,householdId,teen.id,{action:'reinforce',conceptId,completed:true})).status).toBe(403)});
 it('rejects forged answers, repeated submissions and context spoofing',async ()=>{const {teen,householdId}=(await setup());const c={action:'start',mode:'Sign Snap',conceptId};const key=randomUUID();const s=(await run(teen,householdId,teen.id,c,key)) as {result:LearningSession};expect((await run(teen,householdId,teen.id,c,key))).toEqual(s);expect((await run(teen,householdId,teen.id,{...c,mode:'Signal Sense'},key)).status).toBe(409);const answer={action:'answer',sessionId:s.result.id,challengeId:s.result.challengeIds[0],answerId:'meaning'};expect((await run(teen,householdId,teen.id,{...answer,answerId:'forged'})).status).toBe(409);expect((await run(teen,householdId,teen.id,{...answer,correct:true})).status).toBe(400);expect((await run(teen,householdId,teen.id,{...answer,context:'DRIVING'})).status).toBe(400);expect((await run(teen,householdId,teen.id,answer)).status).toBe(200);expect((await run(teen,householdId,teen.id,answer)).status).toBe(409);expect((await all('roadready_attempt'))).toHaveLength(1)});
 it('database triggers prohibit mutation/deletion of both evidence kinds',async ()=>{const {parent,teen,householdId}=(await setup());(await readRoadReady(teen,householdId,teen.id));(await run(parent,householdId,teen.id,{action:'reinforce',conceptId,completed:true}));(await put('roadready_attempt',{...observation(1),householdId,ownerId:teen.id,teenId:teen.id}));for(const kind of ['roadready_attempt','roadready_guardian']){await expect((async()=>(await db().prepare('DELETE FROM records WHERE kind=?').run(kind)))()).rejects.toThrow('append only');await expect((async()=>(await db().prepare("UPDATE records SET payload='{}' WHERE kind=?").run(kind)))()).rejects.toThrow('append only')}});
 it('end-to-end distinct days demonstrate, guardian reinforces with separate evidence',async ()=>{vi.useFakeTimers();const {parent,teen,householdId}=(await setup());for(let day=1;day<=3;day++){vi.setSystemTime(new Date(Date.UTC(2026,8,day)));const s=(await run(teen,householdId,teen.id,{action:'start',mode:'Sign Snap',conceptId})) as {result:LearningSession};expect((await run(teen,householdId,teen.id,{action:'answer',sessionId:s.result.id,challengeId:s.result.challengeIds[0],answerId:'meaning'})).status).toBe(200)}expect((await readRoadReady(teen,householdId,teen.id)).data?.mastery.find(m=>m.conceptId===conceptId)?.state).toBe('demonstrated');vi.setSystemTime(new Date(Date.UTC(2026,8,4)));expect((await run(parent,householdId,teen.id,{action:'reinforce',conceptId,completed:true})).status).toBe(200);expect((await readRoadReady(teen,householdId,teen.id)).data?.mastery.find(m=>m.conceptId===conceptId)?.state).toBe('reinforced');expect((await all('roadready_attempt'))).toHaveLength(3);expect((await all('roadready_guardian'))).toHaveLength(1)});
});
