import {randomBytes,randomUUID} from 'node:crypto';import {z} from 'zod';
import {all,owned,get,put,transaction,db} from '../platform/db';import {AppError,hash} from '../platform/auth';import {requireAdmin} from '../platform/admin';import {ageOn} from '../platform/journey';import {authorizeLearner} from '../platform/authorization';import {audit} from '../platform/service';import type {Member,Profile,Relationship,User} from '../platform/types';import {reviewCatalog} from '../roadready/review-service';import {acknowledgements,acknowledgementVersion,type Cohort,type Enrollment,type PilotInvite} from './types';
const id=z.string().uuid();const command=z.discriminatedUnion('action',[
 z.object({action:z.literal('cohort'),name:z.string().trim().min(2).max(80)}).strict(),
 z.object({action:z.literal('invite'),cohortId:id,email:z.string().email().max(254)}).strict(),
 z.object({action:z.literal('enroll'),householdId:id,token:z.string().min(20).max(100)}).strict(),
 z.object({action:z.literal('acknowledge'),householdId:id,jurisdiction:z.enum(['TX','OTHER']),accepted:z.literal(true),orientation:z.literal(true)}).strict(),
 z.object({action:z.literal('status'),householdId:id,status:z.enum(['active','paused','completed','withdrawn'])}).strict(),
 z.object({action:z.literal('teen_orientation'),householdId:id}).strict(),
 z.object({action:z.literal('feedback'),householdId:id,teenId:id,itemId:z.string(),category:z.enum(['question_unclear','asset_incorrect','explanation_confusing','possible_legal_issue']),note:z.string().trim().min(5).max(500)}).strict(),
 z.object({action:z.literal('feedback_review'),feedbackId:id,decision:z.enum(['review_required','resolved']),note:z.string().trim().min(5).max(500)}).strict(),
]);
const now=()=>new Date().toISOString();const base=(householdId:string,ownerId:string)=>({id:randomUUID(),householdId,ownerId});
async function scope(user:User,householdId:string,guardian=false){const m=(await owned<Member>('member',householdId,user.id)).find(m=>m.active);if(!m||guardian&&m.role!=='guardian')throw new AppError('Pilot household access denied.',403);if(await db().prepare("SELECT 1 FROM records WHERE kind='drive' AND json_extract(payload,'$.status')='active' AND (json_extract(payload,'$.teenId')=? OR json_extract(payload,'$.supervisorId')=?)").get(user.id,user.id))throw new AppError('Resume after parking.',403);return m}
async function event(h:string,user:string,name:string){await put('pilot_event',{...base(h,user),name,at:now()})}
export async function pilotView(user:User,householdId:string){if(process.env.PILOT_ENABLED!=='true')throw new AppError('Pilot enrollment is disabled.',404);return transaction(async()=>{const member=await scope(user,householdId);if(!['guardian','teen'].includes(member.role))throw new AppError('Pilot access denied.',403);const e=(await all<Enrollment>('pilot_enrollment',householdId))[0];const links=(await all<Relationship>('relationship',householdId)).filter(r=>r.active&&r.kind==='guardian'&&r.adultId===user.id);const profiles=(await all<Profile>('profile',householdId)).filter(p=>member.role==='teen'?p.ownerId===user.id:links.some(r=>r.teenId===p.ownerId)&&(ageOn(p.birthDate)<18||p.adultSharing));const orientations=await all<{ownerId:string}>('pilot_orientation',householdId);return {role:member.role,enrollment:e||null,acknowledgements,acknowledgementVersion,checklist:{guardianAccount:member.role==='guardian',household:true,teenLinked:profiles.length>0,teenOrientation:profiles.length>0&&profiles.every(p=>orientations.some(o=>o.ownerId===p.ownerId)),jurisdiction:e?.jurisdiction==='TX',safetyAcknowledged:e?.ackVersion===acknowledgementVersion,orientations:e?.orientation||false,active:e?.status==='active'},teenOriented:orientations.some(o=>o.ownerId===user.id),learners:profiles.map(p=>({id:p.ownerId,name:p.name,jurisdiction:p.jurisdiction,consent:ageOn(p.birthDate)>=18||p.consent}))}})}
export async function pilotCommand(user:User,raw:unknown,key:string){if(process.env.PILOT_ENABLED!=='true')throw new AppError('Pilot enrollment is disabled.',404);const parsed=command.safeParse(raw);if(!parsed.success)throw new AppError('Invalid pilot command.');if(!/^[a-zA-Z0-9_-]{16,100}$/.test(key))throw new AppError('Request key required.');const c=parsed.data;return transaction(async()=>{
 if('householdId' in c)await scope(user,c.householdId,!['feedback','teen_orientation'].includes(c.action));else requireAdmin(user);
 const prior=await db().prepare('SELECT fingerprint,result FROM requests WHERE user_id=? AND key=?').get(user.id,key);const fingerprint=hash(JSON.stringify(c));if(prior){if(prior.fingerprint!==fingerprint)throw new AppError('Request key already used.',409);return JSON.parse(String(prior.result))}
 let result:unknown;
 if(c.action==='cohort')result=await put<Cohort>('pilot_cohort',{...base('',user.id),name:c.name,status:'active'});
 else if(c.action==='invite'){const cohort=await get<Cohort>('pilot_cohort',c.cohortId);if(cohort?.status!=='active')throw new AppError('Active cohort required.',409);const token=randomBytes(32).toString('base64url');await put<PilotInvite>('pilot_invite',{...base('',user.id),email:c.email.toLowerCase(),cohortId:c.cohortId,hash:hash(token),expiresAt:new Date(Date.now()+7*86400000).toISOString(),status:'invited'});result={token};await event('',user.id,'pilot_households_invited')}
 else if(c.action==='enroll'){const invite=(await all<PilotInvite>('pilot_invite')).find(i=>i.hash===hash(c.token));if(!invite||invite.status!=='invited'||invite.expiresAt<=now()||invite.email!==user.email.toLowerCase())throw new AppError('Invitation unavailable for this account.',403);if((await all('pilot_enrollment',c.householdId)).length)throw new AppError('Household already enrolled.',409);result=await put<Enrollment>('pilot_enrollment',{...base(c.householdId,user.id),cohortId:invite.cohortId,status:'onboarding',jurisdiction:'',orientation:false,createdAt:now(),updatedAt:now()});await put('pilot_invite',{...invite,status:'consumed',acceptedBy:user.id});await event(c.householdId,user.id,'guardian_activated')}
 else if(c.action==='acknowledge'||c.action==='status'){const e=(await all<Enrollment>('pilot_enrollment',c.householdId))[0];if(!e)throw new AppError('Pilot invitation required.',409);if(c.action==='acknowledge'){if(e.status!=='onboarding'&&e.status!=='paused')throw new AppError('Onboarding is not open.',409);if(c.jurisdiction!=='TX')throw new AppError('The initial pilot supports Texas only. No Texas rules will be substituted.',409);result=await put('pilot_enrollment',{...e,jurisdiction:c.jurisdiction,ackVersion:acknowledgementVersion,acknowledgedAt:now(),orientation:true,updatedAt:now()})}else{const transitions:Record<string,string[]>={onboarding:['active','withdrawn'],active:['paused','completed','withdrawn'],paused:['active','withdrawn'],completed:[],withdrawn:[]};if(!transitions[e.status]?.includes(c.status))throw new AppError('Invalid pilot transition.',409);if(c.status==='active'){const view=await pilotView(user,c.householdId);if(!view.checklist.teenLinked||!view.checklist.teenOrientation||!view.checklist.safetyAcknowledged||!view.checklist.orientations||!view.checklist.jurisdiction||view.learners.some(p=>p.jurisdiction!=='TX'||!p.consent))throw new AppError('Complete linked learner profiles, Texas jurisdiction, consent and orientation first.',409)}result=await put('pilot_enrollment',{...e,status:c.status,updatedAt:now()});await event(c.householdId,user.id,c.status==='active'?'pilot_households_activated':`pilot_${c.status}`)}}
 else if(c.action==='teen_orientation'){const m=await scope(user,c.householdId);if(m.role!=='teen')throw new AppError('Learner orientation requires the learner account.',403);const ctx=await authorizeLearner(user,c.householdId,user.id);const enrollment=(await all<Enrollment>('pilot_enrollment',c.householdId))[0];if(!enrollment||!['onboarding','active'].includes(enrollment.status)||(ageOn(ctx.profile.birthDate)<18&&!ctx.profile.consent))throw new AppError('Active onboarding and learner consent required.',403);result=await put('pilot_orientation',{id:`orientation:${c.householdId}:${user.id}`,householdId:c.householdId,ownerId:user.id,at:now()});await event(c.householdId,user.id,'teen_onboarding_completed')}
 else if(c.action==='feedback'){const ctx=await authorizeLearner(user,c.householdId,c.teenId);const enrollment=(await all<Enrollment>('pilot_enrollment',c.householdId))[0];if(enrollment?.status!=='active'||(ageOn(ctx.profile.birthDate)<18&&!ctx.profile.consent))throw new AppError('Active pilot and learner consent required.',403);if(await db().prepare("SELECT 1 FROM records WHERE kind='drive' AND json_extract(payload,'$.status')='active' AND json_extract(payload,'$.teenId')=?").get(c.teenId))throw new AppError('Resume after parking.',403);const entry=reviewCatalog().find(e=>e.item.id===c.itemId);if(!entry)throw new AppError('Unknown content item.',404);result=await put('content_feedback',{...base(c.householdId,user.id),teenId:c.teenId,itemId:c.itemId,digest:entry.digest,category:c.category,note:c.note,status:'review_required',at:now()});await audit(user.id,c.householdId,'content.feedback','ALLOW','Feedback queued; publication unchanged.')}
 else{const f=await get<{id:string;householdId:string;ownerId:string;status:string}>('content_feedback',c.feedbackId);if(!f)throw new AppError('Feedback unavailable.',404);result=await put('content_feedback',{...f,status:c.decision,reviewNote:c.note,reviewedBy:user.id,reviewedAt:now()});await audit(user.id,'','feedback.review','ALLOW','Feedback reviewed; content changes require separate version review.')}
 await audit(user.id,'householdId'in c?c.householdId:'',`pilot.${c.action}`,'ALLOW','Authorized scoped pilot command.');await db().prepare('INSERT INTO requests VALUES(?,?,?,?)').run(user.id,key,fingerprint,JSON.stringify(result));return result;}).catch(async error=>{if(error instanceof AppError)await audit(user.id,'householdId' in c?c.householdId:'',`pilot.${c.action}`,'DENY',error.message);throw error})}
