'use client';
import {useState} from 'react';
import {SiteHeader} from '@/components/SiteHeader';
import {SiteFooter} from '@/components/SiteFooter';
import '../landing.css';

const usStates=['Alabama','Alaska','Arizona','Arkansas','California','Colorado','Connecticut','Delaware','District of Columbia','Florida','Georgia','Hawaii','Idaho','Illinois','Indiana','Iowa','Kansas','Kentucky','Louisiana','Maine','Maryland','Massachusetts','Michigan','Minnesota','Mississippi','Missouri','Montana','Nebraska','Nevada','New Hampshire','New Jersey','New Mexico','New York','North Carolina','North Dakota','Ohio','Oklahoma','Oregon','Pennsylvania','Rhode Island','South Carolina','South Dakota','Tennessee','Texas','Utah','Vermont','Virginia','Washington','West Virginia','Wisconsin','Wyoming'];
const canadaRegions=['Alberta','British Columbia','Manitoba','New Brunswick','Newfoundland and Labrador','Northwest Territories','Nova Scotia','Nunavut','Ontario','Prince Edward Island','Quebec','Saskatchewan','Yukon'];

export default function WaitlistPage(){
 const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [done,setDone]=useState(false);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage('');const form=e.currentTarget;const f=new FormData(form);try{const r=await fetch('/api/waitlist',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:f.get('email'),parentName:f.get('parentName'),teenCount:Number(f.get('teenCount')),region:f.get('region'),referralSource:f.get('referralSource'),consent:f.get('consent')==='on',website:f.get('website')})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Unable to join the waitlist.');setDone(true);setMessage("You're on the list. We'll contact you when a pilot spot is available.");form.reset()}catch(error){setMessage(error instanceof Error?error.message:'Unable to join the waitlist.')}finally{setBusy(false)}}
 return <div className="landing waitlistPage"><SiteHeader/><main id="main"><section className="landing-faq" aria-labelledby="waitlist-heading"><div className="landing-faq-intro"><p className="landing-eyebrow">EARLY ACCESS</p><h1 id="waitlist-heading" style={{fontSize:'clamp(48px,6vw,86px)',lineHeight:.92,letterSpacing:'-.06em',margin:'20px 0'}}>JOIN THE<br/>TEENSURANCE <span className="waitlistAccent">WAITLIST.</span></h1><p>Be first to hear about family pilot openings. Joining the waitlist does not determine insurance eligibility, pricing, licensing readiness, or driving risk.</p></div><div>{done?<div role="status" className="waitlistSuccess"><h2>Thanks for joining.</h2><p>{message}</p></div>:<form onSubmit={submit} className="waitlistForm" style={{maxWidth:560}}><label>Parent or guardian name<input name="parentName" required minLength={2} maxLength={100} autoComplete="name"/></label><label>Email<input name="email" type="email" required maxLength={254} autoComplete="email"/></label><label>Number of teen drivers<input name="teenCount" type="number" min={1} max={10} defaultValue={1} required/></label><label>State / province / region<select name="region" required defaultValue="" autoComplete="address-level1"><option value="" disabled>Select your region</option><optgroup label="United States">{usStates.map(region=><option key={region} value={region}>{region}</option>)}</optgroup><optgroup label="Canada">{canadaRegions.map(region=><option key={region} value={region}>{region}</option>)}</optgroup><optgroup label="Other"><option value="Other / International">Other / International</option></optgroup></select></label><label>How did you hear about us? <span style={{fontWeight:400}}>(optional)</span><input name="referralSource" maxLength={80}/></label><input name="website" tabIndex={-1} autoComplete="off" aria-hidden="true" style={{position:'absolute',left:'-9999px'}}/><label><input type="checkbox" name="consent" required/> I agree to be contacted about Teensurance pilot availability and product updates.</label><button className="landing-button" disabled={busy}>{busy?'Joining…':'Join waitlist'}</button><p role="status">{message}</p></form>}</div></section></main><SiteFooter/></div>
}
